-- =========================================================
-- AIBAR — SISTEMA DE TRAZABILIDAD DE PALETS
-- BASE COMPLETA PARA UN PROYECTO NUEVO
-- =========================================================
--
-- QUÉ ES ESTE ARCHIVO
--
-- Todo el esquema en un solo script: tablas, índices,
-- funciones, triggers, vistas, permisos y policies de RLS.
-- No trae un solo dato: ni usuarios, ni productos, ni
-- clientes, ni palets. La base queda vacía y lista.
--
-- Es el schema original más las ocho migraciones que se
-- fueron aplicando, en el mismo orden en que se aplicaron.
-- Corriéndolo entero se llega exactamente al estado actual.
--
--
-- CÓMO SE CORRE
--
-- En el SQL Editor de Supabase, sobre un proyecto NUEVO y
-- vacío. Se pega completo y se ejecuta de una sola vez.
--
-- ⚠️ Sobre un proyecto que ya tenga datos, no. Hay DROPs de
-- vistas y de funciones acá adentro.
--
-- Los NOTICE del tipo «policy … does not exist, skipping» son
-- normales: el script está escrito para poder recorrerse dos
-- veces sin romperse.
--
-- Probado de punta a punta contra un Postgres 17 limpio: las
-- 8 tablas quedan con RLS, las 2 vistas con security_invoker,
-- y el circuito real (alta de palet, descuento de stock, baja,
-- observaciones) funciona con los permisos puestos.
--
--
-- DESPUÉS DE CORRERLO
--
-- La base queda sin un solo usuario, y como el registro
-- público está cerrado a propósito, no hay forma de crear el
-- primero desde la app. Hay que crearlo a mano:
--
--   1. Authentication → Users → Add user, con un email real
--      y su contraseña. El trigger le crea la fila en
--      `public.usuario` con rol 'operario'.
--   2. Volver acá y correr:
--
--        UPDATE public.usuario
--           SET rol = 'jefe', nombre = 'Nombre Apellido'
--         WHERE id = '<el uuid que quedó en Authentication>';
--
-- Ese primer jefe entra con su email. De ahí en más, las
-- altas las hace él desde el panel administrativo y son por
-- DNI.
--
-- =========================================================




-- #########################################################
-- PARTE 1 DE 9 — BASE — TABLAS, FUNCIONES, TRIGGERS Y RLS
-- origen: aibar_schema_completo.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- SISTEMA DE TRAZABILIDAD DE PALETS
-- SUPABASE / POSTGRESQL
-- =========================================================


-- =========================================================
-- ROLES Y REGLAS DEL SISTEMA
-- =========================================================
--
-- OPERARIO:
--   - Crear/modificar/eliminar productos
--   - Crear/modificar/eliminar palets (excepto stock)
--   - Crear/modificar/eliminar detalles
--   - Registrar movimientos
--   - Corregir el último movimiento (ventana de 30 min)
--   - Consultar información
--
-- JEFE:
--   - Consultar toda la información
--   - Buscar y filtrar
--   - Ver movimientos
--   - No modificar información
--
-- STOCK:
--   cantidad_inicial      -> solo al crear palet
--   cantidad_disponible   -> registrar_movimiento() / corregir_movimiento()
--   estado                -> registrar_movimiento() / corregir_movimiento()
--
-- MOVIMIENTOS:
--   - Se crean únicamente mediante registrar_movimiento()
--     o corregir_movimiento()
--   - No se pueden modificar
--   - No se pueden eliminar
--
-- TIPOS DE MOVIMIENTO:
--   - venta        -> resta stock
--   - salida       -> resta stock
--   - ajuste       -> resta stock
--   - correccion   -> suma stock (solo vía corregir_movimiento)
--
-- IMPORTANTE:
--   venta / salida / ajuste SIEMPRE restan stock.
--   Solo 'correccion' puede sumar, y solo la puede generar
--   la función corregir_movimiento(), nunca un INSERT directo
--   ni registrar_movimiento().
--
-- Para ingresar stock nuevo (mercadería que llega) se debe
-- crear un nuevo palet.
--
-- =========================================================


-- =========================================================
-- 1. USUARIOS
-- =========================================================

CREATE TABLE public.usuario (
    id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    nombre VARCHAR(100) NOT NULL,

    rol VARCHAR(20) NOT NULL
        CHECK (
            rol IN ('operario', 'jefe')
        ),

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 2. PRODUCTOS
-- =========================================================

CREATE TABLE public.producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,

    categoria VARCHAR(20) NOT NULL
        CHECK (
            categoria IN (
                'agroquimico',
                'semilla'
            )
        ),

    unidad_medida VARCHAR(20) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 3. PALETS
-- =========================================================

CREATE TABLE public.palet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    producto_id BIGINT NOT NULL
        REFERENCES public.producto(id)
        ON DELETE RESTRICT,

    lote VARCHAR(50) NOT NULL,

    cantidad_inicial NUMERIC(10,2) NOT NULL
        CHECK (
            cantidad_inicial > 0
        ),

    cantidad_disponible NUMERIC(10,2) NOT NULL
        CHECK (
            cantidad_disponible >= 0
            AND cantidad_disponible <= cantidad_inicial
        ),

    galpon SMALLINT NOT NULL
        CHECK (
            galpon IN (1, 2, 3)
        ),

    sector VARCHAR(50),

    fecha_ingreso DATE NOT NULL
        DEFAULT CURRENT_DATE,

    estado VARCHAR(20) NOT NULL
        DEFAULT 'activo'
        CHECK (
            estado IN (
                'activo',
                'parcial',
                'vacio',
                'baja'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW()
);


-- =========================================================
-- 4. DETALLE AGROQUÍMICO
-- =========================================================

CREATE TABLE public.detalle_agroquimico (
    palet_id BIGINT PRIMARY KEY
        REFERENCES public.palet(id)
        ON DELETE CASCADE,

    fecha_elaboracion DATE,

    fecha_vencimiento DATE,

    CHECK (
        fecha_vencimiento IS NULL
        OR fecha_elaboracion IS NULL
        OR fecha_vencimiento >= fecha_elaboracion
    )
);


-- =========================================================
-- 5. DETALLE SEMILLA
-- =========================================================

CREATE TABLE public.detalle_semilla (
    palet_id BIGINT PRIMARY KEY
        REFERENCES public.palet(id)
        ON DELETE CASCADE,

    hibrido VARCHAR(100),

    calibre VARCHAR(50)
);


-- =========================================================
-- 6. MOVIMIENTOS
-- =========================================================
--
-- HISTORIAL INMUTABLE
--
-- Nunca se actualiza.
-- Nunca se elimina.
--
-- corrige_a: si el movimiento es una 'correccion', apunta
-- al movimiento original que está corrigiendo. NULL en
-- cualquier otro caso.
--
-- motivo: obligatorio solo para 'correccion', para dejar
-- registrado por qué se corrigió.
--
-- =========================================================

CREATE TABLE public.movimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    palet_id BIGINT NOT NULL
        REFERENCES public.palet(id)
        ON DELETE RESTRICT,

    usuario_id UUID NOT NULL
        REFERENCES public.usuario(id)
        ON DELETE RESTRICT,

    tipo VARCHAR(20) NOT NULL
        CHECK (
            tipo IN (
                'venta',
                'salida',
                'ajuste',
                'correccion'
            )
        ),

    cantidad NUMERIC(10,2) NOT NULL
        CHECK (
            cantidad > 0
        ),

    corrige_a BIGINT
        REFERENCES public.movimiento(id),

    motivo VARCHAR(255),

    fecha_hora TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    CHECK (
        tipo <> 'correccion' OR motivo IS NOT NULL
    ),

    CHECK (
        tipo = 'correccion' OR corrige_a IS NULL
    )
);


-- =========================================================
-- 7. ÍNDICES
-- =========================================================

CREATE INDEX idx_palet_producto
    ON public.palet(producto_id);

CREATE INDEX idx_palet_estado
    ON public.palet(estado);

CREATE INDEX idx_palet_galpon
    ON public.palet(galpon);

CREATE INDEX idx_palet_lote
    ON public.palet(lote);

CREATE INDEX idx_palet_fecha_ingreso
    ON public.palet(fecha_ingreso);

CREATE INDEX idx_movimiento_palet
    ON public.movimiento(palet_id);

CREATE INDEX idx_movimiento_usuario
    ON public.movimiento(usuario_id);

CREATE INDEX idx_movimiento_fecha
    ON public.movimiento(fecha_hora);

CREATE INDEX idx_movimiento_corrige_a
    ON public.movimiento(corrige_a);


-- =========================================================
-- 8. UPDATED_AT
-- =========================================================

CREATE OR REPLACE FUNCTION public.actualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();

    RETURN NEW;
END;
$$;


CREATE TRIGGER trigger_palet_updated_at
BEFORE UPDATE ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_updated_at();


-- =========================================================
-- 9. FUNCIONES DE AUTORIZACIÓN
-- =========================================================

CREATE OR REPLACE FUNCTION public.usuario_activo()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.usuario
        WHERE id = auth.uid()
        AND activo = TRUE
    );
$$;


CREATE OR REPLACE FUNCTION public.es_operario()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.usuario
        WHERE id = auth.uid()
        AND rol = 'operario'
        AND activo = TRUE
    );
$$;


CREATE OR REPLACE FUNCTION public.es_jefe()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.usuario
        WHERE id = auth.uid()
        AND rol = 'jefe'
        AND activo = TRUE
    );
$$;


-- =========================================================
-- 10. CREAR USUARIO AUTOMÁTICAMENTE
-- =========================================================
--
-- Todo usuario registrado empieza como OPERARIO.
--
-- Para convertirlo en jefe:
--
-- UPDATE public.usuario
-- SET rol = 'jefe'
-- WHERE id = 'UUID';
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.crear_usuario()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN

    INSERT INTO public.usuario (
        id,
        nombre,
        rol,
        activo
    )
    VALUES (
        NEW.id,

        COALESCE(
            NEW.raw_user_meta_data ->> 'nombre',
            NEW.email
        ),

        'operario',

        TRUE
    );

    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_crear_usuario
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.crear_usuario();


-- =========================================================
-- 11. INICIALIZAR PALET
-- =========================================================
--
-- Al crear un palet:
--
-- cantidad_disponible = cantidad_inicial
-- estado = activo
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.inicializar_palet()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    NEW.cantidad_disponible :=
        NEW.cantidad_inicial;

    NEW.estado := 'activo';

    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_inicializar_palet
BEFORE INSERT ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.inicializar_palet();


-- =========================================================
-- 12. PROTEGER DATOS DE STOCK
-- =========================================================
--
-- Impide modificar directamente:
--
--   cantidad_inicial
--   cantidad_disponible
--   estado
--
-- registrar_movimiento() y corregir_movimiento() son los
-- únicos mecanismos autorizados para modificar
-- cantidad_disponible y estado (ambos corren como
-- SECURITY DEFINER, por eso current_user != session_user
-- cuando pasan por acá y no disparan la excepción).
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.proteger_stock_palet()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    IF NEW.cantidad_inicial IS DISTINCT FROM OLD.cantidad_inicial THEN
        RAISE EXCEPTION
            'La cantidad inicial no puede modificarse después de crear el palet';
    END IF;

    IF (
        NEW.cantidad_disponible IS DISTINCT FROM OLD.cantidad_disponible
        OR NEW.estado IS DISTINCT FROM OLD.estado
    )
    AND current_user = session_user THEN

        RAISE EXCEPTION
            'El stock solo puede modificarse mediante registrar_movimiento() o corregir_movimiento()';

    END IF;

    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_proteger_stock_palet
BEFORE UPDATE ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.proteger_stock_palet();


-- =========================================================
-- 12.5. PROTEGER IDENTIDAD DEL PALET
-- =========================================================
--
-- Un palet que ya tiene movimientos no puede cambiar:
--   - producto
--   - lote
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.proteger_identidad_palet()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_categoria_nueva VARCHAR(20);
    v_tiene_movimientos BOOLEAN;
    v_tiene_detalle_agro BOOLEAN;
    v_tiene_detalle_semilla BOOLEAN;
BEGIN

    IF NEW.producto_id IS DISTINCT FROM OLD.producto_id
       OR NEW.lote IS DISTINCT FROM OLD.lote THEN

        SELECT EXISTS (
            SELECT 1
            FROM public.movimiento
            WHERE palet_id = OLD.id
        )
        INTO v_tiene_movimientos;

        IF v_tiene_movimientos THEN
            RAISE EXCEPTION
                'No se puede cambiar producto o lote de un palet que ya tiene movimientos';
        END IF;

    END IF;


    IF NEW.producto_id IS DISTINCT FROM OLD.producto_id THEN

        SELECT categoria
        INTO v_categoria_nueva
        FROM public.producto
        WHERE id = NEW.producto_id;

        IF v_categoria_nueva IS NULL THEN
            RAISE EXCEPTION
                'El producto indicado no existe';
        END IF;


        SELECT EXISTS (
            SELECT 1
            FROM public.detalle_agroquimico
            WHERE palet_id = OLD.id
        )
        INTO v_tiene_detalle_agro;


        SELECT EXISTS (
            SELECT 1
            FROM public.detalle_semilla
            WHERE palet_id = OLD.id
        )
        INTO v_tiene_detalle_semilla;


        IF v_categoria_nueva <> 'agroquimico'
           AND v_tiene_detalle_agro THEN

            RAISE EXCEPTION
                'No se puede cambiar el producto: el palet tiene un detalle agroquímico';

        END IF;


        IF v_categoria_nueva <> 'semilla'
           AND v_tiene_detalle_semilla THEN

            RAISE EXCEPTION
                'No se puede cambiar el producto: el palet tiene un detalle de semilla';

        END IF;

    END IF;


    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_proteger_identidad_palet
BEFORE UPDATE ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.proteger_identidad_palet();


-- =========================================================
-- 13. VALIDAR DETALLE AGROQUÍMICO
-- =========================================================

CREATE OR REPLACE FUNCTION public.validar_detalle_agroquimico()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_categoria VARCHAR(20);
BEGIN

    SELECT p.categoria
    INTO v_categoria
    FROM public.palet pa
    INNER JOIN public.producto p
        ON p.id = pa.producto_id
    WHERE pa.id = NEW.palet_id;


    IF v_categoria IS NULL THEN
        RAISE EXCEPTION
            'El palet no existe';
    END IF;


    IF v_categoria <> 'agroquimico' THEN
        RAISE EXCEPTION
            'El palet no corresponde a un producto agroquímico';
    END IF;


    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_validar_detalle_agroquimico
BEFORE INSERT OR UPDATE ON public.detalle_agroquimico
FOR EACH ROW
EXECUTE FUNCTION public.validar_detalle_agroquimico();


-- =========================================================
-- 14. VALIDAR DETALLE SEMILLA
-- =========================================================

CREATE OR REPLACE FUNCTION public.validar_detalle_semilla()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_categoria VARCHAR(20);
BEGIN

    SELECT p.categoria
    INTO v_categoria
    FROM public.palet pa
    INNER JOIN public.producto p
        ON p.id = pa.producto_id
    WHERE pa.id = NEW.palet_id;


    IF v_categoria IS NULL THEN
        RAISE EXCEPTION
            'El palet no existe';
    END IF;


    IF v_categoria <> 'semilla' THEN
        RAISE EXCEPTION
            'El palet no corresponde a un producto semilla';
    END IF;


    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_validar_detalle_semilla
BEFORE INSERT OR UPDATE ON public.detalle_semilla
FOR EACH ROW
EXECUTE FUNCTION public.validar_detalle_semilla();


-- =========================================================
-- 15. PROTEGER CATEGORÍA DE PRODUCTOS
-- =========================================================
--
-- Una vez que un producto tiene palets asociados,
-- su categoría no puede cambiar.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.proteger_categoria_producto()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    IF NEW.categoria IS DISTINCT FROM OLD.categoria THEN

        IF EXISTS (
            SELECT 1
            FROM public.palet
            WHERE producto_id = OLD.id
        ) THEN

            RAISE EXCEPTION
                'No se puede cambiar la categoría de un producto que ya tiene palets asociados';

        END IF;

    END IF;


    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_proteger_categoria_producto
BEFORE UPDATE ON public.producto
FOR EACH ROW
EXECUTE FUNCTION public.proteger_categoria_producto();


-- =========================================================
-- 16. REGISTRAR MOVIMIENTO
-- =========================================================
--
-- ESTA FUNCIÓN MODIFICA:
--
--   cantidad_disponible
--   estado
--
-- Además crea el registro histórico.
--
-- Todo ocurre dentro de una única transacción.
--
-- TODOS LOS TIPOS RESTAN STOCK:
--
--   venta  -> resta stock
--   salida -> resta stock
--   ajuste -> resta stock
--
-- Para corregir un error de tipeo (sumar stock), no se usa
-- esta función: se usa corregir_movimiento() (sección 16.5).
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.registrar_movimiento(
    p_palet_id BIGINT,
    p_tipo VARCHAR,
    p_cantidad NUMERIC
)
RETURNS public.movimiento
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$

DECLARE
    v_usuario_id UUID;
    v_palet public.palet%ROWTYPE;
    v_nueva_cantidad NUMERIC;
    v_nuevo_estado VARCHAR(20);
    v_movimiento public.movimiento%ROWTYPE;

BEGIN

    -- =====================================================
    -- 1. Usuario autenticado
    -- =====================================================

    v_usuario_id := auth.uid();

    IF v_usuario_id IS NULL THEN
        RAISE EXCEPTION
            'Usuario no autenticado';
    END IF;


    -- =====================================================
    -- 2. Verificar operario
    -- =====================================================

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION
            'Solo los operarios pueden registrar movimientos';
    END IF;


    -- =====================================================
    -- 3. Validar tipo
    -- =====================================================

    IF p_tipo NOT IN (
        'venta',
        'salida',
        'ajuste'
    ) THEN

        RAISE EXCEPTION
            'Tipo de movimiento inválido';

    END IF;


    -- =====================================================
    -- 4. Validar cantidad
    -- =====================================================

    IF p_cantidad IS NULL
       OR p_cantidad <= 0 THEN

        RAISE EXCEPTION
            'La cantidad debe ser mayor que cero';

    END IF;


    -- =====================================================
    -- 5. Obtener palet y bloquearlo
    -- =====================================================
    --
    -- FOR UPDATE evita problemas si dos operarios
    -- intentan modificar el mismo palet al mismo tiempo.
    --
    -- =====================================================

    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = p_palet_id
    FOR UPDATE;


    IF NOT FOUND THEN
        RAISE EXCEPTION
            'El palet no existe';
    END IF;


    -- =====================================================
    -- 6. Verificar estado
    -- =====================================================

    IF v_palet.estado = 'baja' THEN
        RAISE EXCEPTION
            'El palet se encuentra dado de baja';
    END IF;


    IF v_palet.cantidad_disponible = 0 THEN
        RAISE EXCEPTION
            'El palet no tiene stock disponible';
    END IF;


    -- =====================================================
    -- 7. Verificar stock suficiente
    -- =====================================================

    IF p_cantidad > v_palet.cantidad_disponible THEN

        RAISE EXCEPTION
            'Stock insuficiente. Disponible: %, solicitado: %',
            v_palet.cantidad_disponible,
            p_cantidad;

    END IF;


    -- =====================================================
    -- 8. CALCULAR NUEVO STOCK (siempre se resta)
    -- =====================================================

    v_nueva_cantidad :=
        v_palet.cantidad_disponible - p_cantidad;


    -- =====================================================
    -- 9. DETERMINAR NUEVO ESTADO
    -- =====================================================

    IF v_nueva_cantidad = 0 THEN

        v_nuevo_estado := 'vacio';

    ELSIF v_nueva_cantidad <
          v_palet.cantidad_inicial THEN

        v_nuevo_estado := 'parcial';

    ELSE

        v_nuevo_estado := 'activo';

    END IF;


    -- =====================================================
    -- 10. ACTUALIZAR PALET
    -- =====================================================

    UPDATE public.palet
    SET
        cantidad_disponible = v_nueva_cantidad,
        estado = v_nuevo_estado
    WHERE id = p_palet_id;


    -- =====================================================
    -- 11. CREAR HISTORIAL
    -- =====================================================

    INSERT INTO public.movimiento (
        palet_id,
        usuario_id,
        tipo,
        cantidad
    )
    VALUES (
        p_palet_id,
        v_usuario_id,
        p_tipo,
        p_cantidad
    )
    RETURNING *
    INTO v_movimiento;


    -- =====================================================
    -- 12. DEVOLVER MOVIMIENTO
    -- =====================================================

    RETURN v_movimiento;

END;
$$;


-- =========================================================
-- 16.5. CORREGIR MOVIMIENTO (deshacer un error de tipeo)
-- =========================================================
--
-- Única función que puede sumar stock. No reemplaza ni
-- edita el movimiento original: crea un movimiento nuevo,
-- de tipo 'correccion', que lo compensa. El historial
-- completo queda intacto y auditable.
--
-- Restricciones:
--   - Solo puede corregir el ÚLTIMO movimiento del palet
--     (no cualquiera del historial).
--   - Solo dentro de los 30 minutos posteriores a su carga.
--   - No se puede corregir una corrección.
--   - El motivo es obligatorio (queda guardado en movimiento.motivo).
--
-- El botón "corregir" del front debe llamar únicamente a
-- esta función, nunca insertar un 'ajuste' con signo
-- invertido ni tocar el palet directamente.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.corregir_movimiento(
    p_movimiento_id BIGINT,
    p_motivo VARCHAR
)
RETURNS public.movimiento
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$

DECLARE
    v_usuario_id UUID;
    v_original public.movimiento%ROWTYPE;
    v_ultimo_id BIGINT;
    v_palet public.palet%ROWTYPE;
    v_nueva_cantidad NUMERIC;
    v_nuevo_estado VARCHAR(20);
    v_movimiento public.movimiento%ROWTYPE;

BEGIN

    -- =====================================================
    -- 1. Usuario autenticado y operario
    -- =====================================================

    v_usuario_id := auth.uid();

    IF v_usuario_id IS NULL THEN
        RAISE EXCEPTION
            'Usuario no autenticado';
    END IF;

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION
            'Solo los operarios pueden corregir movimientos';
    END IF;


    -- =====================================================
    -- 2. Validar motivo
    -- =====================================================

    IF p_motivo IS NULL OR btrim(p_motivo) = '' THEN
        RAISE EXCEPTION
            'Es obligatorio indicar el motivo de la corrección';
    END IF;


    -- =====================================================
    -- 3. Obtener el movimiento original
    -- =====================================================

    SELECT *
    INTO v_original
    FROM public.movimiento
    WHERE id = p_movimiento_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'El movimiento no existe';
    END IF;

    IF v_original.tipo = 'correccion' THEN
        RAISE EXCEPTION
            'No se puede corregir una corrección';
    END IF;


    -- =====================================================
    -- 4. Debe ser el ÚLTIMO movimiento de ese palet
    -- =====================================================

    SELECT id
    INTO v_ultimo_id
    FROM public.movimiento
    WHERE palet_id = v_original.palet_id
    ORDER BY fecha_hora DESC
    LIMIT 1;

    IF v_ultimo_id IS DISTINCT FROM p_movimiento_id THEN
        RAISE EXCEPTION
            'Solo se puede corregir el último movimiento registrado en el palet';
    END IF;


    -- =====================================================
    -- 5. Ventana de tiempo: 30 minutos
    -- =====================================================

    IF NOW() - v_original.fecha_hora > INTERVAL '30 minutes' THEN
        RAISE EXCEPTION
            'El movimiento ya no puede corregirse (fuera de plazo)';
    END IF;


    -- =====================================================
    -- 6. Bloquear el palet y recalcular stock
    -- =====================================================

    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = v_original.palet_id
    FOR UPDATE;

    v_nueva_cantidad :=
        v_palet.cantidad_disponible + v_original.cantidad;

    IF v_nueva_cantidad > v_palet.cantidad_inicial THEN
        RAISE EXCEPTION
            'La corrección dejaría el stock por encima de la cantidad inicial del palet';
    END IF;

    IF v_nueva_cantidad = v_palet.cantidad_inicial THEN
        v_nuevo_estado := 'activo';
    ELSIF v_nueva_cantidad = 0 THEN
        v_nuevo_estado := 'vacio';
    ELSE
        v_nuevo_estado := 'parcial';
    END IF;


    -- =====================================================
    -- 7. Actualizar palet
    -- =====================================================

    UPDATE public.palet
    SET
        cantidad_disponible = v_nueva_cantidad,
        estado = v_nuevo_estado
    WHERE id = v_original.palet_id;


    -- =====================================================
    -- 8. Crear el movimiento de corrección
    -- =====================================================

    INSERT INTO public.movimiento (
        palet_id,
        usuario_id,
        tipo,
        cantidad,
        corrige_a,
        motivo
    )
    VALUES (
        v_original.palet_id,
        v_usuario_id,
        'correccion',
        v_original.cantidad,
        p_movimiento_id,
        p_motivo
    )
    RETURNING *
    INTO v_movimiento;


    RETURN v_movimiento;

END;
$$;


-- =========================================================
-- 17. ACTIVAR RLS
-- =========================================================

ALTER TABLE public.usuario
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.producto
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.palet
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.detalle_agroquimico
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.detalle_semilla
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.movimiento
ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 18. USUARIO - POLICIES
-- =========================================================

CREATE POLICY "usuario_select"
ON public.usuario
FOR SELECT
TO authenticated
USING (
    id = auth.uid()
    OR public.es_jefe()
);


-- =========================================================
-- 19. PRODUCTO - POLICIES
-- =========================================================

CREATE POLICY "producto_select"
ON public.producto
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


CREATE POLICY "producto_insert_operario"
ON public.producto
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "producto_update_operario"
ON public.producto
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "producto_delete_operario"
ON public.producto
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 20. PALET - POLICIES
-- =========================================================

CREATE POLICY "palet_select"
ON public.palet
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


CREATE POLICY "palet_insert_operario"
ON public.palet
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "palet_update_operario"
ON public.palet
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "palet_delete_operario"
ON public.palet
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 21. DETALLE AGROQUÍMICO - POLICIES
-- =========================================================

CREATE POLICY "agroquimico_select"
ON public.detalle_agroquimico
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


CREATE POLICY "agroquimico_insert_operario"
ON public.detalle_agroquimico
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "agroquimico_update_operario"
ON public.detalle_agroquimico
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "agroquimico_delete_operario"
ON public.detalle_agroquimico
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 22. DETALLE SEMILLA - POLICIES
-- =========================================================

CREATE POLICY "semilla_select"
ON public.detalle_semilla
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


CREATE POLICY "semilla_insert_operario"
ON public.detalle_semilla
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "semilla_update_operario"
ON public.detalle_semilla
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "semilla_delete_operario"
ON public.detalle_semilla
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 23. MOVIMIENTO - POLICIES
-- =========================================================
--
-- Todos los usuarios activos pueden consultar.
--
-- Nadie puede insertar directamente.
-- Nadie puede modificar.
-- Nadie puede eliminar.
--
-- registrar_movimiento() y corregir_movimiento() son los
-- únicos caminos (ambos SECURITY DEFINER).
--
-- =========================================================

CREATE POLICY "movimiento_select"
ON public.movimiento
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


-- =========================================================
-- 24. PERMISOS DE COLUMNAS DE PALET
-- =========================================================
--
-- El usuario autenticado NO tiene UPDATE general.
--
-- Solo puede modificar:
--
--   producto_id
--   lote
--   galpon
--   sector
--   fecha_ingreso
--
-- cantidad_inicial:
--   nunca
--
-- cantidad_disponible / estado:
--   registrar_movimiento() / corregir_movimiento()
--
-- =========================================================

REVOKE UPDATE
ON public.palet
FROM authenticated;


GRANT UPDATE (
    producto_id,
    lote,
    galpon,
    sector,
    fecha_ingreso
)
ON public.palet
TO authenticated;


-- =========================================================
-- 25. MOVIMIENTO: BLOQUEAR CRUD DIRECTO
-- =========================================================

REVOKE INSERT
ON public.movimiento
FROM authenticated;

REVOKE UPDATE
ON public.movimiento
FROM authenticated;

REVOKE DELETE
ON public.movimiento
FROM authenticated;


-- =========================================================
-- 26. SEGURIDAD DE FUNCIONES SECURITY DEFINER
-- =========================================================

REVOKE ALL
ON FUNCTION public.registrar_movimiento(BIGINT, VARCHAR, NUMERIC)
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.corregir_movimiento(BIGINT, VARCHAR)
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.usuario_activo()
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.es_operario()
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.es_jefe()
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.crear_usuario()
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.proteger_identidad_palet()
FROM PUBLIC;


-- =========================================================
-- 27. EJECUCIÓN DE FUNCIONES
-- =========================================================

GRANT EXECUTE
ON FUNCTION public.registrar_movimiento(
    BIGINT,
    VARCHAR,
    NUMERIC
)
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.corregir_movimiento(
    BIGINT,
    VARCHAR
)
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.usuario_activo()
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.es_operario()
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.es_jefe()
TO authenticated;


-- =========================================================
-- 28. BLOQUEAR FUNCIONES PARA ANÓNIMOS
-- =========================================================

REVOKE EXECUTE
ON FUNCTION public.registrar_movimiento(
    BIGINT,
    VARCHAR,
    NUMERIC
)
FROM anon;


REVOKE EXECUTE
ON FUNCTION public.corregir_movimiento(
    BIGINT,
    VARCHAR
)
FROM anon;


REVOKE EXECUTE
ON FUNCTION public.usuario_activo()
FROM anon;


REVOKE EXECUTE
ON FUNCTION public.es_operario()
FROM anon;


REVOKE EXECUTE
ON FUNCTION public.es_jefe()
FROM anon;


-- =========================================================
-- FIN
-- =========================================================


-- #########################################################
-- PARTE 2 DE 9 — ALTA DE PALET COMPLETO
-- origen: supabase/migrations/20260811120000_crear_palet_completo.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- ALTA DE PALET COMPLETO (palet + detalle)
-- =========================================================
--
-- PROBLEMA QUE RESUELVE
--
-- Un palet y su detalle son una sola cosa desde el punto de
-- vista del negocio, pero viven en dos tablas. Desde el
-- cliente eso son dos requests HTTP contra PostgREST, y
-- PostgREST no puede envolver dos requests en una misma
-- transacción: entre el INSERT del palet y el del detalle
-- hay una ventana en la que el palet existe incompleto, y
-- si la red se corta ahí, queda así para siempre.
--
-- Esta función hace los dos INSERT dentro de una única
-- transacción. O se crean los dos, o no se crea ninguno.
--
--
-- SEGURIDAD: SECURITY INVOKER (el valor por omisión)
--
-- A diferencia de registrar_movimiento() y
-- corregir_movimiento(), esta función NO es SECURITY
-- DEFINER, y es a propósito.
--
-- Aquellas necesitan DEFINER porque tienen que saltear el
-- trigger proteger_stock_palet(). Esta no necesita saltear
-- nada: el operario ya tiene permiso de INSERT por las
-- policies palet_insert_operario, agroquimico_insert_operario
-- y semilla_insert_operario.
--
-- Con INVOKER, RLS se sigue aplicando adentro de la función.
-- Ponerle DEFINER abriría un agujero: cualquier usuario
-- autenticado podría crear palets salteándose su policy.
--
--
-- STOCK
--
-- No se pasan cantidad_disponible ni estado: los fija el
-- trigger inicializar_palet() a partir de cantidad_inicial.
-- Mandarlos sería redundante y frágil.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.crear_palet_completo(
    p_producto_id BIGINT,
    p_lote VARCHAR,
    p_cantidad_inicial NUMERIC,
    p_galpon SMALLINT,
    p_sector VARCHAR DEFAULT NULL,
    p_fecha_ingreso DATE DEFAULT NULL,

    -- Solo se usan si el producto es agroquímico
    p_fecha_elaboracion DATE DEFAULT NULL,
    p_fecha_vencimiento DATE DEFAULT NULL,

    -- Solo se usan si el producto es semilla
    p_hibrido VARCHAR DEFAULT NULL,
    p_calibre VARCHAR DEFAULT NULL
)
RETURNS public.palet
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$

DECLARE
    v_categoria VARCHAR(20);
    v_palet public.palet%ROWTYPE;

BEGIN

    -- =====================================================
    -- 1. Verificar operario
    -- =====================================================
    --
    -- Las policies ya lo impedirían, pero el error que
    -- devuelve RLS ('new row violates row-level security
    -- policy') no le dice nada al operario. Este chequeo
    -- existe solo para dar un mensaje legible.
    --
    -- =====================================================

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION
            'Solo los operarios pueden dar de alta palets';
    END IF;


    -- =====================================================
    -- 2. Obtener la categoría del producto
    -- =====================================================
    --
    -- Es la que decide qué tabla de detalle corresponde.
    --
    -- =====================================================

    SELECT categoria
    INTO v_categoria
    FROM public.producto
    WHERE id = p_producto_id;

    IF v_categoria IS NULL THEN
        RAISE EXCEPTION
            'El producto indicado no existe';
    END IF;


    -- =====================================================
    -- 3. Crear el palet
    -- =====================================================
    --
    -- Sin cantidad_disponible ni estado: los pone el
    -- trigger inicializar_palet().
    --
    -- =====================================================

    INSERT INTO public.palet (
        producto_id,
        lote,
        cantidad_inicial,
        galpon,
        sector,
        fecha_ingreso
    )
    VALUES (
        p_producto_id,
        p_lote,
        p_cantidad_inicial,
        p_galpon,
        NULLIF(btrim(p_sector), ''),
        COALESCE(p_fecha_ingreso, CURRENT_DATE)
    )
    RETURNING *
    INTO v_palet;


    -- =====================================================
    -- 4. Crear el detalle que corresponda
    -- =====================================================
    --
    -- Se inserta siempre, aunque sus campos vengan en NULL,
    -- para que todo palet tenga la fila de detalle de su
    -- categoría y las consultas posteriores sean uniformes.
    --
    -- Los campos de la otra categoría se ignoran. Si igual
    -- se colaran, los triggers validar_detalle_agroquimico()
    -- y validar_detalle_semilla() los rechazarían.
    --
    -- =====================================================

    IF v_categoria = 'agroquimico' THEN

        INSERT INTO public.detalle_agroquimico (
            palet_id,
            fecha_elaboracion,
            fecha_vencimiento
        )
        VALUES (
            v_palet.id,
            p_fecha_elaboracion,
            p_fecha_vencimiento
        );

    ELSIF v_categoria = 'semilla' THEN

        INSERT INTO public.detalle_semilla (
            palet_id,
            hibrido,
            calibre
        )
        VALUES (
            v_palet.id,
            NULLIF(btrim(p_hibrido), ''),
            NULLIF(btrim(p_calibre), '')
        );

    ELSE

        RAISE EXCEPTION
            'Categoría de producto desconocida: %',
            v_categoria;

    END IF;


    -- =====================================================
    -- 5. Devolver el palet creado
    -- =====================================================
    --
    -- Se relee para que cantidad_disponible y estado vengan
    -- con los valores que puso el trigger, y no con los que
    -- tenía la fila antes de dispararse.
    --
    -- =====================================================

    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = v_palet.id;

    RETURN v_palet;

END;
$$;


-- =========================================================
-- PERMISOS
-- =========================================================

REVOKE ALL
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR
)
FROM PUBLIC;


GRANT EXECUTE
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR
)
TO authenticated;


REVOKE EXECUTE
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR
)
FROM anon;


-- =========================================================
-- FIN
-- =========================================================


-- #########################################################
-- PARTE 3 DE 9 — VISIBILIDAD DE USUARIOS ENTRE SÍ
-- origen: supabase/migrations/20260812150000_usuarios_visibles_entre_si.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- VISIBILIDAD DE USUARIOS ENTRE SÍ
-- =========================================================
--
-- PROBLEMA QUE RESUELVE
--
-- La policy original solo dejaba a cada usuario ver su propia
-- fila:
--
--   USING (id = auth.uid() OR public.es_jefe())
--
-- Con eso, el historial de movimientos de un palet no puede
-- mostrar quién registró cada uno: un operario lee los
-- movimientos (la policy movimiento_select se lo permite)
-- pero al resolver el usuario asociado recibe NULL para
-- todos los que no son él.
--
-- Y saber quién movió el stock es justamente lo que sirve
-- cuando aparece un faltante.
--
--
-- POR QUÉ ES SEGURO
--
-- La tabla `usuario` no guarda datos sensibles: solo nombre,
-- rol, si está activo y cuándo se creó. El email y las
-- credenciales viven en auth.users, que sigue siendo
-- inaccesible desde el cliente.
--
-- La visibilidad se limita a usuarios activos: alguien dado
-- de baja no ve nada, igual que antes.
--
-- Esto NO habilita modificar usuarios. Sigue sin haber
-- policies de INSERT, UPDATE ni DELETE sobre esta tabla: el
-- alta la hace el trigger crear_usuario() y los cambios de
-- rol se hacen a mano contra la base.
--
-- =========================================================

DROP POLICY IF EXISTS "usuario_select" ON public.usuario;


CREATE POLICY "usuario_select"
ON public.usuario
FOR SELECT
TO authenticated
USING (
    -- La fila propia se ve siempre, incluso estando inactivo:
    -- es lo que permite mostrar la pantalla "cuenta sin acceso"
    -- con el nombre de quien entró.
    id = auth.uid()

    -- El resto del padrón, solo para usuarios activos.
    OR public.usuario_activo()
);


-- =========================================================
-- FIN
-- =========================================================


-- #########################################################
-- PARTE 4 DE 9 — NOMBRE DE PRODUCTO ÚNICO
-- origen: supabase/migrations/20260812180000_producto_nombre_unico.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- NOMBRE DE PRODUCTO ÚNICO
-- =========================================================
--
-- OPCIONAL. Aplicala solo si querés que la base impida los
-- productos duplicados.
--
--
-- PROBLEMA QUE RESUELVE
--
-- La pantalla de alta avisa si ya existe un producto con el
-- mismo nombre, pero esa comprobación es del lado del
-- cliente: consulta, y después inserta. Entre esas dos
-- cosas, otro operario puede haber insertado el mismo
-- producto, y los dos pasan.
--
-- El resultado son dos filas «Glifosato 48%» con ids
-- distintos, y palets repartidos entre ambas: los listados y
-- cualquier total por producto quedan partidos al medio.
--
-- Un índice único lo vuelve imposible, porque la
-- verificación pasa a ocurrir dentro de la misma transacción
-- que el INSERT.
--
--
-- POR QUÉ ES SOBRE lower(trim(...))
--
-- Sin normalizar, «Glifosato 48%», «glifosato 48%» y
-- «Glifosato 48% » serían tres productos distintos para
-- Postgres, que es justo lo que se quiere evitar. El índice
-- funcional compara el nombre sin espacios de sobra ni
-- diferencias de mayúsculas.
--
--
-- ANTES DE APLICARLA
--
-- Si ya hay duplicados cargados, el índice no se va a poder
-- crear. Para encontrarlos:
--
--   SELECT lower(btrim(nombre)) AS nombre_normalizado,
--          count(*),
--          array_agg(id) AS ids
--   FROM public.producto
--   GROUP BY 1
--   HAVING count(*) > 1;
--
-- Hay que unificarlos a mano antes: repuntar los palets al
-- id que quede (UPDATE public.palet SET producto_id = ...)
-- y recién ahí borrar el sobrante.
--
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS producto_nombre_unico
ON public.producto (lower(btrim(nombre)));


-- =========================================================
-- FIN
-- =========================================================


-- #########################################################
-- PARTE 5 DE 9 — VISTAS DEL PANEL DE GERENCIA
-- origen: supabase/migrations/20260812200000_vistas_gerencia.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- VISTAS PARA EL PANEL DE GERENCIA
-- =========================================================
--
-- El panel del jefe no pregunta «qué palets hay»: pregunta
-- qué se está por vencer, qué no se mueve y cuánto hay de
-- cada producto. Todas esas respuestas cruzan palet con
-- producto, con el detalle de agroquímico y con la última
-- fecha de movimiento.
--
-- Esos cruces se hacen en la base y no en el navegador. Si
-- se resolvieran en el cliente habría que descargar todos
-- los palets, todos sus detalles y todos sus movimientos en
-- cada apertura del panel, para después agrupar en un
-- celular. Postgres ya sabe hacerlo, y con los índices que
-- el schema tiene.
--
--
-- ⚠️ SEGURIDAD: security_invoker
--
-- Por omisión, una vista de Postgres se ejecuta con los
-- permisos de QUIEN LA CREÓ, no de quien la consulta. Eso
-- saltearía las policies RLS por completo: un usuario
-- inactivo, o el rol anónimo, verían el depósito entero.
--
-- `security_invoker = on` hace que la vista corra con los
-- permisos de quien consulta, así RLS se sigue aplicando
-- sobre las tablas de abajo exactamente igual que hoy.
--
-- Requiere PostgreSQL 15 o superior. Si esta migración falla
-- con «unrecognized parameter security_invoker», la base es
-- anterior y NO hay que quitar la opción para que pase:
-- habría que resolverlo con funciones en vez de vistas.
--
-- =========================================================


-- =========================================================
-- 1. PALETS ENRIQUECIDOS
-- =========================================================
--
-- Un palet con todo lo que el panel necesita para decidir,
-- ya resuelto: su producto, su vencimiento si es
-- agroquímico, y hace cuánto que no se mueve.
--
-- =========================================================

CREATE OR REPLACE VIEW public.vista_palet_gerencia
WITH (security_invoker = on)
AS
SELECT
    p.id,
    p.producto_id,
    p.lote,
    p.cantidad_inicial,
    p.cantidad_disponible,
    p.galpon,
    p.sector,
    p.fecha_ingreso,
    p.estado,

    pr.nombre         AS producto_nombre,
    pr.categoria      AS producto_categoria,
    pr.unidad_medida  AS producto_unidad_medida,

    da.fecha_elaboracion,
    da.fecha_vencimiento,
    ds.hibrido,
    ds.calibre,

    -- Negativo = ya vencido. NULL en semillas y en
    -- agroquímicos sin fecha cargada.
    (da.fecha_vencimiento - CURRENT_DATE) AS dias_para_vencer,

    ultimo.fecha_hora AS ultimo_movimiento,

    -- Un palet que nunca se movió está quieto desde que
    -- entró: por eso el fallback a fecha_ingreso.
    (CURRENT_DATE - COALESCE(ultimo.fecha_hora::date, p.fecha_ingreso))
        AS dias_sin_movimiento

FROM public.palet p

INNER JOIN public.producto pr
    ON pr.id = p.producto_id

LEFT JOIN public.detalle_agroquimico da
    ON da.palet_id = p.id

LEFT JOIN public.detalle_semilla ds
    ON ds.palet_id = p.id

LEFT JOIN LATERAL (
    SELECT max(m.fecha_hora) AS fecha_hora
    FROM public.movimiento m
    WHERE m.palet_id = p.id
) ultimo ON TRUE;


-- =========================================================
-- 2. STOCK CONSOLIDADO POR PRODUCTO
-- =========================================================
--
-- Responde «¿tengo para cubrir este pedido?» sin recorrer
-- palet por palet, y muestra en cuántos está repartido: un
-- producto con 400 litros en un palet no es lo mismo que
-- con 400 repartidos en ocho abiertos a medias.
--
-- =========================================================

CREATE OR REPLACE VIEW public.vista_stock_por_producto
WITH (security_invoker = on)
AS
SELECT
    pr.id             AS producto_id,
    pr.nombre         AS producto_nombre,
    pr.categoria      AS producto_categoria,
    pr.unidad_medida  AS producto_unidad_medida,

    COALESCE(sum(p.cantidad_disponible), 0) AS total_disponible,

    count(p.id) FILTER (
        WHERE p.estado IN ('activo', 'parcial')
    ) AS palets_con_stock,

    count(p.id) FILTER (
        WHERE p.estado = 'parcial'
    ) AS palets_parciales,

    -- En qué galpones está repartido.
    COALESCE(
        array_agg(DISTINCT p.galpon) FILTER (
            WHERE p.estado IN ('activo', 'parcial')
        ),
        '{}'
    ) AS galpones,

    -- El vencimiento más próximo entre los palets que
    -- todavía tienen stock: es el que marca la urgencia.
    min(da.fecha_vencimiento) FILTER (
        WHERE p.estado IN ('activo', 'parcial')
    ) AS proximo_vencimiento

FROM public.producto pr

LEFT JOIN public.palet p
    ON p.producto_id = pr.id

LEFT JOIN public.detalle_agroquimico da
    ON da.palet_id = p.id

GROUP BY pr.id, pr.nombre, pr.categoria, pr.unidad_medida;


-- =========================================================
-- 3. PERMISOS
-- =========================================================
--
-- Solo lectura, y para usuarios autenticados. RLS sobre las
-- tablas de abajo sigue filtrando gracias a security_invoker,
-- así que un usuario inactivo no ve nada.
--
-- =========================================================

GRANT SELECT ON public.vista_palet_gerencia TO authenticated;
GRANT SELECT ON public.vista_stock_por_producto TO authenticated;

REVOKE ALL ON public.vista_palet_gerencia FROM anon;
REVOKE ALL ON public.vista_stock_por_producto FROM anon;


-- =========================================================
-- FIN
-- =========================================================


-- #########################################################
-- PARTE 6 DE 9 — CLIENTES Y OBSERVACIONES
-- origen: supabase/migrations/20260812210000_clientes_y_observaciones.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- CLIENTES Y OBSERVACIONES DE PALET
-- =========================================================
--
-- Dos necesidades que aparecieron con el uso real:
--
-- 1. El depósito guarda mercadería de terceros. Hay que
--    poder decir de quién es cada palet, y consultar qué
--    hay de cada cliente.
--
-- 2. A un palet le pasan cosas —bidones pinchados, envases
--    rotos, humedad— y hay que poder anotarlas en cualquier
--    momento, no solo al darlo de alta.
--
-- Las observaciones van como bitácora y no como un campo de
-- texto en `palet`: cada nota queda con quién la escribió y
-- cuándo. Con un campo único, el segundo operario que anota
-- pisa lo que puso el primero y se pierde la historia, que
-- es justamente lo que se quiere conservar.
--
-- =========================================================


-- =========================================================
-- 1. CLIENTES
-- =========================================================
--
-- Solo el nombre: es lo que hace falta para saber de quién
-- es la mercadería. Si más adelante se necesita CUIT o
-- contacto, se suman columnas sin romper nada.
--
-- =========================================================

CREATE TABLE IF NOT EXISTS public.cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- Mismo criterio que en producto: no queremos dos veces el
-- mismo cliente escrito distinto.
CREATE UNIQUE INDEX IF NOT EXISTS cliente_nombre_unico
ON public.cliente (lower(btrim(nombre)));


ALTER TABLE public.cliente
ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS "cliente_select" ON public.cliente;

CREATE POLICY "cliente_select"
ON public.cliente
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


DROP POLICY IF EXISTS "cliente_insert_operario" ON public.cliente;

CREATE POLICY "cliente_insert_operario"
ON public.cliente
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


DROP POLICY IF EXISTS "cliente_update_operario" ON public.cliente;

CREATE POLICY "cliente_update_operario"
ON public.cliente
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


DROP POLICY IF EXISTS "cliente_delete_operario" ON public.cliente;

CREATE POLICY "cliente_delete_operario"
ON public.cliente
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 2. DUEÑO DEL PALET
-- =========================================================
--
-- Nullable a propósito: sin cliente, la mercadería es de
-- AIBAR. Es el caso más común, y obligar a elegir en cada
-- alta sería fricción para nada.
--
-- ON DELETE RESTRICT: no se puede borrar un cliente que
-- todavía tiene mercadería en el depósito.
--
-- =========================================================

ALTER TABLE public.palet
ADD COLUMN IF NOT EXISTS cliente_id BIGINT
    REFERENCES public.cliente(id)
    ON DELETE RESTRICT;


CREATE INDEX IF NOT EXISTS idx_palet_cliente
ON public.palet(cliente_id);


-- El dueño se puede corregir, igual que el galpón o el
-- sector. Sumarlo al GRANT de columnas de la sección 24 del
-- schema original.
GRANT UPDATE (cliente_id)
ON public.palet
TO authenticated;


-- =========================================================
-- 3. OBSERVACIONES
-- =========================================================
--
-- Historial de notas sobre el palet. Inmutables, como los
-- movimientos: si una nota estaba equivocada, se agrega otra
-- aclarándolo. Así la bitácora refleja lo que se supo en
-- cada momento y no se puede reescribir la historia.
--
-- =========================================================

CREATE TABLE IF NOT EXISTS public.observacion_palet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    palet_id BIGINT NOT NULL
        REFERENCES public.palet(id)
        ON DELETE CASCADE,

    usuario_id UUID NOT NULL
        REFERENCES public.usuario(id)
        ON DELETE RESTRICT,

    texto VARCHAR(500) NOT NULL
        CHECK (btrim(texto) <> ''),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_observacion_palet
ON public.observacion_palet(palet_id);


ALTER TABLE public.observacion_palet
ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS "observacion_select" ON public.observacion_palet;

CREATE POLICY "observacion_select"
ON public.observacion_palet
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


-- Solo operarios, y solo a nombre propio: nadie puede dejar
-- una nota firmada por otro.
DROP POLICY IF EXISTS "observacion_insert_operario" ON public.observacion_palet;

CREATE POLICY "observacion_insert_operario"
ON public.observacion_palet
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
    AND usuario_id = auth.uid()
);


-- Sin policies de UPDATE ni DELETE: las notas no se editan
-- ni se borran.
REVOKE UPDATE, DELETE
ON public.observacion_palet
FROM authenticated;


-- =========================================================
-- 4. ALTA DE PALET CON CLIENTE Y PRIMERA OBSERVACIÓN
-- =========================================================
--
-- Hay que recrear la función porque cambia su firma, y
-- CREATE OR REPLACE no permite agregar parámetros.
--
-- Sigue siendo SECURITY INVOKER: no saltea nada, RLS se
-- aplica igual que antes.
--
-- =========================================================

DROP FUNCTION IF EXISTS public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR
);


CREATE OR REPLACE FUNCTION public.crear_palet_completo(
    p_producto_id BIGINT,
    p_lote VARCHAR,
    p_cantidad_inicial NUMERIC,
    p_galpon SMALLINT,
    p_sector VARCHAR DEFAULT NULL,
    p_fecha_ingreso DATE DEFAULT NULL,

    -- Solo se usan si el producto es agroquímico
    p_fecha_elaboracion DATE DEFAULT NULL,
    p_fecha_vencimiento DATE DEFAULT NULL,

    -- Solo se usan si el producto es semilla
    p_hibrido VARCHAR DEFAULT NULL,
    p_calibre VARCHAR DEFAULT NULL,

    -- NULL = mercadería propia de AIBAR
    p_cliente_id BIGINT DEFAULT NULL,

    -- Primera nota de la bitácora. Opcional.
    p_observacion VARCHAR DEFAULT NULL
)
RETURNS public.palet
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$

DECLARE
    v_categoria VARCHAR(20);
    v_palet public.palet%ROWTYPE;
    v_observacion VARCHAR(500);

BEGIN

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION
            'Solo los operarios pueden dar de alta palets';
    END IF;


    SELECT categoria
    INTO v_categoria
    FROM public.producto
    WHERE id = p_producto_id;

    IF v_categoria IS NULL THEN
        RAISE EXCEPTION
            'El producto indicado no existe';
    END IF;


    IF p_cliente_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM public.cliente WHERE id = p_cliente_id
       ) THEN
        RAISE EXCEPTION
            'El cliente indicado no existe';
    END IF;


    INSERT INTO public.palet (
        producto_id,
        lote,
        cantidad_inicial,
        galpon,
        sector,
        fecha_ingreso,
        cliente_id
    )
    VALUES (
        p_producto_id,
        p_lote,
        p_cantidad_inicial,
        p_galpon,
        NULLIF(btrim(p_sector), ''),
        COALESCE(p_fecha_ingreso, CURRENT_DATE),
        p_cliente_id
    )
    RETURNING *
    INTO v_palet;


    IF v_categoria = 'agroquimico' THEN

        INSERT INTO public.detalle_agroquimico (
            palet_id,
            fecha_elaboracion,
            fecha_vencimiento
        )
        VALUES (
            v_palet.id,
            p_fecha_elaboracion,
            p_fecha_vencimiento
        );

    ELSIF v_categoria = 'semilla' THEN

        INSERT INTO public.detalle_semilla (
            palet_id,
            hibrido,
            calibre
        )
        VALUES (
            v_palet.id,
            NULLIF(btrim(p_hibrido), ''),
            NULLIF(btrim(p_calibre), '')
        );

    ELSE

        RAISE EXCEPTION
            'Categoría de producto desconocida: %',
            v_categoria;

    END IF;


    -- La observación inicial entra en la misma transacción
    -- que el palet: o queda todo, o no queda nada.
    v_observacion := NULLIF(btrim(p_observacion), '');

    IF v_observacion IS NOT NULL THEN

        INSERT INTO public.observacion_palet (
            palet_id,
            usuario_id,
            texto
        )
        VALUES (
            v_palet.id,
            auth.uid(),
            v_observacion
        );

    END IF;


    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = v_palet.id;

    RETURN v_palet;

END;
$$;


REVOKE ALL
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR, BIGINT, VARCHAR
)
FROM PUBLIC;


GRANT EXECUTE
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR, BIGINT, VARCHAR
)
TO authenticated;


REVOKE EXECUTE
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR, BIGINT, VARCHAR
)
FROM anon;


-- =========================================================
-- 5. VISTAS DE GERENCIA CON CLIENTE
-- =========================================================
--
-- Se recrean para sumar el dueño del palet y la cantidad de
-- observaciones, que es la señal de que algo pasó con ese
-- palet y conviene abrirlo.
--
-- =========================================================

-- CREATE OR REPLACE solo permite AGREGAR columnas al final: cambiar el orden
-- o insertar una en el medio falla con «cannot change name of view column».
-- Como `cliente_id` va junto al resto de la identificación del palet y no
-- colgada al final, hay que soltar la vista y volver a crearla.
DROP VIEW IF EXISTS public.vista_palet_gerencia;


CREATE VIEW public.vista_palet_gerencia
WITH (security_invoker = on)
AS
SELECT
    p.id,
    p.producto_id,
    p.lote,
    p.cantidad_inicial,
    p.cantidad_disponible,
    p.galpon,
    p.sector,
    p.fecha_ingreso,
    p.estado,

    pr.nombre         AS producto_nombre,
    pr.categoria      AS producto_categoria,
    pr.unidad_medida  AS producto_unidad_medida,

    p.cliente_id,
    c.nombre          AS cliente_nombre,

    da.fecha_elaboracion,
    da.fecha_vencimiento,
    ds.hibrido,
    ds.calibre,

    (da.fecha_vencimiento - CURRENT_DATE) AS dias_para_vencer,

    ultimo.fecha_hora AS ultimo_movimiento,

    (CURRENT_DATE - COALESCE(ultimo.fecha_hora::date, p.fecha_ingreso))
        AS dias_sin_movimiento,

    COALESCE(obs.cantidad, 0) AS cantidad_observaciones

FROM public.palet p

INNER JOIN public.producto pr
    ON pr.id = p.producto_id

LEFT JOIN public.cliente c
    ON c.id = p.cliente_id

LEFT JOIN public.detalle_agroquimico da
    ON da.palet_id = p.id

LEFT JOIN public.detalle_semilla ds
    ON ds.palet_id = p.id

LEFT JOIN LATERAL (
    SELECT max(m.fecha_hora) AS fecha_hora
    FROM public.movimiento m
    WHERE m.palet_id = p.id
) ultimo ON TRUE

LEFT JOIN LATERAL (
    SELECT count(*) AS cantidad
    FROM public.observacion_palet o
    WHERE o.palet_id = p.id
) obs ON TRUE;


GRANT SELECT ON public.vista_palet_gerencia TO authenticated;
REVOKE ALL ON public.vista_palet_gerencia FROM anon;


-- =========================================================
-- FIN
-- =========================================================


-- #########################################################
-- PARTE 7 DE 9 — OBSERVACIONES A LA VISTA EN EL PANEL
-- origen: supabase/migrations/20260812230000_observaciones_en_panel.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- OBSERVACIONES A LA VISTA EN EL PANEL DE GERENCIA
-- =========================================================
--
-- El panel mostraba cuántas observaciones tenía cada palet,
-- pero para leerlas había que entrar uno por uno. Un jefe
-- que quiere saber qué novedades hubo en el depósito no va a
-- abrir treinta palets para averiguarlo.
--
-- La vista pasa a traer la última nota de cada palet —texto,
-- fecha y autor— para que se lea directamente en el listado.
--
-- Se resuelve con un LATERAL en la base y no trayendo todas
-- las observaciones al navegador: así sigue siendo una sola
-- consulta, sin una por palet.
--
-- =========================================================

-- CREATE OR REPLACE no permite insertar columnas en el medio
-- de una vista existente, y estas van junto al resto de la
-- información del palet.
DROP VIEW IF EXISTS public.vista_palet_gerencia;


CREATE VIEW public.vista_palet_gerencia
WITH (security_invoker = on)
AS
SELECT
    p.id,
    p.producto_id,
    p.lote,
    p.cantidad_inicial,
    p.cantidad_disponible,
    p.galpon,
    p.sector,
    p.fecha_ingreso,
    p.estado,

    pr.nombre         AS producto_nombre,
    pr.categoria      AS producto_categoria,
    pr.unidad_medida  AS producto_unidad_medida,

    p.cliente_id,
    c.nombre          AS cliente_nombre,

    da.fecha_elaboracion,
    da.fecha_vencimiento,
    ds.hibrido,
    ds.calibre,

    (da.fecha_vencimiento - CURRENT_DATE) AS dias_para_vencer,

    ultimo.fecha_hora AS ultimo_movimiento,

    (CURRENT_DATE - COALESCE(ultimo.fecha_hora::date, p.fecha_ingreso))
        AS dias_sin_movimiento,

    COALESCE(obs.cantidad, 0) AS cantidad_observaciones,

    -- La última nota, para leerla sin entrar al palet.
    ultima_obs.texto      AS ultima_observacion,
    ultima_obs.created_at AS ultima_observacion_fecha,
    ultima_obs.autor      AS ultima_observacion_autor

FROM public.palet p

INNER JOIN public.producto pr
    ON pr.id = p.producto_id

LEFT JOIN public.cliente c
    ON c.id = p.cliente_id

LEFT JOIN public.detalle_agroquimico da
    ON da.palet_id = p.id

LEFT JOIN public.detalle_semilla ds
    ON ds.palet_id = p.id

LEFT JOIN LATERAL (
    SELECT max(m.fecha_hora) AS fecha_hora
    FROM public.movimiento m
    WHERE m.palet_id = p.id
) ultimo ON TRUE

LEFT JOIN LATERAL (
    SELECT count(*) AS cantidad
    FROM public.observacion_palet o
    WHERE o.palet_id = p.id
) obs ON TRUE

LEFT JOIN LATERAL (
    SELECT
        o.texto,
        o.created_at,
        u.nombre AS autor
    FROM public.observacion_palet o
    LEFT JOIN public.usuario u
        ON u.id = o.usuario_id
    WHERE o.palet_id = p.id
    ORDER BY o.created_at DESC, o.id DESC
    LIMIT 1
) ultima_obs ON TRUE;


GRANT SELECT ON public.vista_palet_gerencia TO authenticated;
REVOKE ALL ON public.vista_palet_gerencia FROM anon;


-- =========================================================
-- FIN
-- =========================================================


-- #########################################################
-- PARTE 8 DE 9 — BAJA DE PALET, PRODUCTO AMPLIADO Y USUARIOS
-- origen: supabase/migrations/20260813100000_baja_producto_y_usuarios.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- BAJA DE PALET, PRODUCTO AMPLIADO Y GESTIÓN DE USUARIOS
-- =========================================================
--
-- Tres huecos que dejó el uso real:
--
-- 1. No había forma de dar de baja un palet desde la app.
--    Mercadería vencida o rota seguía figurando como stock.
--
-- 2. `producto.nombre` era todo lo que había: no se podía
--    filtrar por marca ni por principio activo, que es lo que
--    hace falta para saber qué se puede aplicar y qué se le
--    compró a cada proveedor.
--
-- 3. Los roles se cambiaban con UPDATE manual contra la base.
--
-- =========================================================


-- =========================================================
-- 1. PRODUCTO: MARCA, PRINCIPIO ACTIVO Y CONCENTRACIÓN
-- =========================================================
--
-- Todas opcionales: hay productos cargados sin estos datos y
-- no se los puede obligar a completar retroactivamente.
--
-- El principio activo aplica a los agroquímicos —una semilla
-- no tiene— pero no se fuerza por CHECK: obligar a dejarlo
-- vacío en semillas solo agregaría errores al alta.
--
-- =========================================================

ALTER TABLE public.producto
ADD COLUMN IF NOT EXISTS marca VARCHAR(100);

ALTER TABLE public.producto
ADD COLUMN IF NOT EXISTS principio_activo VARCHAR(150);

ALTER TABLE public.producto
ADD COLUMN IF NOT EXISTS concentracion VARCHAR(50);


-- Para filtrar «todo lo de Bayer» y «todo lo que lleve
-- glifosato» sin recorrer la tabla entera.
CREATE INDEX IF NOT EXISTS idx_producto_marca
ON public.producto(marca);

CREATE INDEX IF NOT EXISTS idx_producto_principio_activo
ON public.producto(principio_activo);


-- =========================================================
-- 2. DAR DE BAJA UN PALET
-- =========================================================
--
-- SECURITY DEFINER, a diferencia de crear_palet_completo():
-- acá SÍ hay que saltear un trigger. proteger_stock_palet()
-- bloquea cualquier cambio de `estado` que venga del cliente,
-- y esta función necesita justamente eso.
--
-- El motivo es obligatorio y queda en la bitácora del palet:
-- dar de baja mercadería es sacarla del stock, y después
-- alguien va a preguntar por qué.
--
-- El stock NO se pone en cero: el palet se congela como
-- estaba. Así queda registrado cuánto había cuando se
-- descartó, que es el dato que importa para saber qué se
-- perdió.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.dar_de_baja_palet(
    p_palet_id BIGINT,
    p_motivo VARCHAR
)
RETURNS public.palet
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$

DECLARE
    v_usuario_id UUID;
    v_palet public.palet%ROWTYPE;
    v_motivo VARCHAR(500);

BEGIN

    v_usuario_id := auth.uid();

    IF v_usuario_id IS NULL THEN
        RAISE EXCEPTION 'Usuario no autenticado';
    END IF;

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION
            'Solo los operarios pueden dar de baja un palet';
    END IF;


    v_motivo := NULLIF(btrim(p_motivo), '');

    IF v_motivo IS NULL THEN
        RAISE EXCEPTION
            'Es obligatorio indicar el motivo de la baja';
    END IF;


    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = p_palet_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'El palet no existe';
    END IF;

    IF v_palet.estado = 'baja' THEN
        RAISE EXCEPTION
            'El palet ya estaba dado de baja';
    END IF;


    UPDATE public.palet
    SET estado = 'baja'
    WHERE id = p_palet_id;


    -- La baja queda explicada en la bitácora, junto al resto
    -- de lo que le pasó al palet.
    INSERT INTO public.observacion_palet (
        palet_id,
        usuario_id,
        texto
    )
    VALUES (
        p_palet_id,
        v_usuario_id,
        'BAJA: ' || v_motivo
    );


    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = p_palet_id;

    RETURN v_palet;

END;
$$;


REVOKE ALL
ON FUNCTION public.dar_de_baja_palet(BIGINT, VARCHAR)
FROM PUBLIC;

GRANT EXECUTE
ON FUNCTION public.dar_de_baja_palet(BIGINT, VARCHAR)
TO authenticated;

REVOKE EXECUTE
ON FUNCTION public.dar_de_baja_palet(BIGINT, VARCHAR)
FROM anon;


-- =========================================================
-- 3. GESTIÓN DE USUARIOS POR EL GERENTE
-- =========================================================
--
-- El jefe puede activar, desactivar y cambiar el rol de los
-- demás. Es la única escritura que se le permite, y es
-- deliberada: sin ella los roles se cambian con SQL manual.
--
-- Lo que NO puede:
--   - Cambiarse el rol a sí mismo ni desactivarse. Un jefe
--     que se quita el rol por error deja el sistema sin nadie
--     que pueda devolvérselo.
--   - Crear usuarios. Eso vive en auth.users y necesita la
--     service_role, que jamás va al navegador: lo hace una
--     Edge Function que valida el rol antes de crear.
--
-- =========================================================

CREATE POLICY "usuario_update_jefe"
ON public.usuario
FOR UPDATE
TO authenticated
USING (
    public.es_jefe()
    AND id <> auth.uid()
)
WITH CHECK (
    public.es_jefe()
    AND id <> auth.uid()
);


-- El nombre y la fecha de alta no se tocan desde la app: lo
-- único administrable es el rol y si está activo.
REVOKE UPDATE
ON public.usuario
FROM authenticated;

GRANT UPDATE (rol, activo)
ON public.usuario
TO authenticated;


-- =========================================================
-- 4. VISTAS: SUMAR LOS DATOS NUEVOS DEL PRODUCTO
-- =========================================================

DROP VIEW IF EXISTS public.vista_palet_gerencia;


CREATE VIEW public.vista_palet_gerencia
WITH (security_invoker = on)
AS
SELECT
    p.id,
    p.producto_id,
    p.lote,
    p.cantidad_inicial,
    p.cantidad_disponible,
    p.galpon,
    p.sector,
    p.fecha_ingreso,
    p.estado,

    pr.nombre         AS producto_nombre,
    pr.categoria      AS producto_categoria,
    pr.unidad_medida  AS producto_unidad_medida,
    pr.marca          AS producto_marca,
    pr.principio_activo AS producto_principio_activo,
    pr.concentracion  AS producto_concentracion,

    p.cliente_id,
    c.nombre          AS cliente_nombre,

    da.fecha_elaboracion,
    da.fecha_vencimiento,
    ds.hibrido,
    ds.calibre,

    (da.fecha_vencimiento - CURRENT_DATE) AS dias_para_vencer,

    ultimo.fecha_hora AS ultimo_movimiento,

    (CURRENT_DATE - COALESCE(ultimo.fecha_hora::date, p.fecha_ingreso))
        AS dias_sin_movimiento,

    COALESCE(obs.cantidad, 0) AS cantidad_observaciones,

    ultima_obs.texto      AS ultima_observacion,
    ultima_obs.created_at AS ultima_observacion_fecha,
    ultima_obs.autor      AS ultima_observacion_autor

FROM public.palet p

INNER JOIN public.producto pr
    ON pr.id = p.producto_id

LEFT JOIN public.cliente c
    ON c.id = p.cliente_id

LEFT JOIN public.detalle_agroquimico da
    ON da.palet_id = p.id

LEFT JOIN public.detalle_semilla ds
    ON ds.palet_id = p.id

LEFT JOIN LATERAL (
    SELECT max(m.fecha_hora) AS fecha_hora
    FROM public.movimiento m
    WHERE m.palet_id = p.id
) ultimo ON TRUE

LEFT JOIN LATERAL (
    SELECT count(*) AS cantidad
    FROM public.observacion_palet o
    WHERE o.palet_id = p.id
) obs ON TRUE

LEFT JOIN LATERAL (
    SELECT o.texto, o.created_at, u.nombre AS autor
    FROM public.observacion_palet o
    LEFT JOIN public.usuario u ON u.id = o.usuario_id
    WHERE o.palet_id = p.id
    ORDER BY o.created_at DESC, o.id DESC
    LIMIT 1
) ultima_obs ON TRUE;


GRANT SELECT ON public.vista_palet_gerencia TO authenticated;
REVOKE ALL ON public.vista_palet_gerencia FROM anon;


DROP VIEW IF EXISTS public.vista_stock_por_producto;


CREATE VIEW public.vista_stock_por_producto
WITH (security_invoker = on)
AS
SELECT
    pr.id             AS producto_id,
    pr.nombre         AS producto_nombre,
    pr.categoria      AS producto_categoria,
    pr.unidad_medida  AS producto_unidad_medida,
    pr.marca          AS producto_marca,
    pr.principio_activo AS producto_principio_activo,
    pr.concentracion  AS producto_concentracion,

    COALESCE(sum(p.cantidad_disponible) FILTER (
        WHERE p.estado IN ('activo', 'parcial')
    ), 0) AS total_disponible,

    count(p.id) FILTER (
        WHERE p.estado IN ('activo', 'parcial')
    ) AS palets_con_stock,

    count(p.id) FILTER (
        WHERE p.estado = 'parcial'
    ) AS palets_parciales,

    COALESCE(
        array_agg(DISTINCT p.galpon) FILTER (
            WHERE p.estado IN ('activo', 'parcial')
        ),
        '{}'
    ) AS galpones,

    min(da.fecha_vencimiento) FILTER (
        WHERE p.estado IN ('activo', 'parcial')
    ) AS proximo_vencimiento

FROM public.producto pr

LEFT JOIN public.palet p
    ON p.producto_id = pr.id

LEFT JOIN public.detalle_agroquimico da
    ON da.palet_id = p.id

GROUP BY pr.id, pr.nombre, pr.categoria, pr.unidad_medida,
         pr.marca, pr.principio_activo, pr.concentracion;


GRANT SELECT ON public.vista_stock_por_producto TO authenticated;
REVOKE ALL ON public.vista_stock_por_producto FROM anon;


-- =========================================================
-- FIN
-- =========================================================


-- #########################################################
-- PARTE 9 DE 9 — INGRESO POR DNI
-- origen: supabase/migrations/20260813140000_login_por_dni.sql
-- #########################################################

-- =========================================================
-- AIBAR
-- INGRESO POR DNI
-- =========================================================
--
-- Los operarios entran con su DNI, no con un email. En el
-- depósito no todos tienen correo, y el DNI es el número que
-- todos saben de memoria y no se olvidan.
--
--
-- CÓMO FUNCIONA
--
-- Supabase Auth solo autentica por email o teléfono: no hay
-- forma de pedirle que valide un campo cualquiera. Así que
-- cada cuenta se crea con un email derivado del DNI:
--
--   DNI 30123456  ->  30123456@aibar.local
--
-- Ese correo no existe ni se usa nunca: no se envían mails y
-- las cuentas se crean ya confirmadas. Es un identificador
-- interno con forma de email, nada más. El dominio `.local`
-- está reservado para redes internas, así que jamás va a
-- chocar con un dominio real.
--
-- El operario nunca lo ve. Escribe su DNI y la app arma el
-- resto.
--
--
-- POR QUÉ TAMBIÉN SE GUARDA EN `usuario`
--
-- Podría deducirse del email, pero tenerlo como columna
-- permite mostrarlo en el panel, buscar por él y garantizar
-- que no se repita con un índice único.
--
-- =========================================================

ALTER TABLE public.usuario
ADD COLUMN IF NOT EXISTS dni VARCHAR(15);


-- Dos personas no pueden compartir DNI, y sin esto dos altas
-- simultáneas podrían colarlo. El índice es parcial porque
-- las cuentas viejas —creadas con email real— lo tienen en
-- NULL y no deben bloquearse entre sí.
CREATE UNIQUE INDEX IF NOT EXISTS usuario_dni_unico
ON public.usuario (dni)
WHERE dni IS NOT NULL;


-- =========================================================
-- ALTA AUTOMÁTICA DEL PERFIL
-- =========================================================
--
-- El trigger que crea la fila en `public.usuario` cuando se
-- registra alguien pasa a copiar también el DNI, que la Edge
-- Function manda en la metadata de la cuenta.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.crear_usuario()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN

    INSERT INTO public.usuario (
        id,
        nombre,
        dni,
        rol,
        activo
    )
    VALUES (
        NEW.id,

        COALESCE(
            NEW.raw_user_meta_data ->> 'nombre',
            NEW.email
        ),

        -- NULL en las cuentas creadas a mano con email real,
        -- como la del primer gerente.
        NULLIF(btrim(COALESCE(NEW.raw_user_meta_data ->> 'dni', '')), ''),

        'operario',

        TRUE
    );

    RETURN NEW;

END;
$$;


REVOKE ALL
ON FUNCTION public.crear_usuario()
FROM PUBLIC;


-- =========================================================
-- FIN
-- =========================================================
