-- =========================================================
-- AIBAR
-- SISTEMA DE TRAZABILIDAD DE PALETS
-- SUPABASE / POSTGRESQL
-- =========================================================


-- =========================================================
-- ROLES Y REGLAS DEL SISTEMA
-- =========================================================
--
-- OPERARIO:
--   - Crear/modificar/eliminar productos
--   - Crear/modificar/eliminar palets (excepto stock)
--   - Crear/modificar/eliminar detalles
--   - Registrar movimientos
--   - Corregir el último movimiento (ventana de 30 min)
--   - Consultar información
--
-- JEFE:
--   - Consultar toda la información
--   - Buscar y filtrar
--   - Ver movimientos
--   - No modificar información
--
-- STOCK:
--   cantidad_inicial      -> solo al crear palet
--   cantidad_disponible   -> registrar_movimiento() / corregir_movimiento()
--   estado                -> registrar_movimiento() / corregir_movimiento()
--
-- MOVIMIENTOS:
--   - Se crean únicamente mediante registrar_movimiento()
--     o corregir_movimiento()
--   - No se pueden modificar
--   - No se pueden eliminar
--
-- TIPOS DE MOVIMIENTO:
--   - venta        -> resta stock
--   - salida       -> resta stock
--   - ajuste       -> resta stock
--   - correccion   -> suma stock (solo vía corregir_movimiento)
--
-- IMPORTANTE:
--   venta / salida / ajuste SIEMPRE restan stock.
--   Solo 'correccion' puede sumar, y solo la puede generar
--   la función corregir_movimiento(), nunca un INSERT directo
--   ni registrar_movimiento().
--
-- Para ingresar stock nuevo (mercadería que llega) se debe
-- crear un nuevo palet.
--
-- =========================================================


-- =========================================================
-- 1. USUARIOS
-- =========================================================

CREATE TABLE public.usuario (
    id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    nombre VARCHAR(100) NOT NULL,

    rol VARCHAR(20) NOT NULL
        CHECK (
            rol IN ('operario', 'jefe')
        ),

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 2. PRODUCTOS
-- =========================================================

CREATE TABLE public.producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,

    categoria VARCHAR(20) NOT NULL
        CHECK (
            categoria IN (
                'agroquimico',
                'semilla'
            )
        ),

    unidad_medida VARCHAR(20) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 3. PALETS
-- =========================================================

CREATE TABLE public.palet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    producto_id BIGINT NOT NULL
        REFERENCES public.producto(id)
        ON DELETE RESTRICT,

    lote VARCHAR(50) NOT NULL,

    cantidad_inicial NUMERIC(10,2) NOT NULL
        CHECK (
            cantidad_inicial > 0
        ),

    cantidad_disponible NUMERIC(10,2) NOT NULL
        CHECK (
            cantidad_disponible >= 0
            AND cantidad_disponible <= cantidad_inicial
        ),

    galpon SMALLINT NOT NULL
        CHECK (
            galpon IN (1, 2, 3)
        ),

    sector VARCHAR(50),

    fecha_ingreso DATE NOT NULL
        DEFAULT CURRENT_DATE,

    estado VARCHAR(20) NOT NULL
        DEFAULT 'activo'
        CHECK (
            estado IN (
                'activo',
                'parcial',
                'vacio',
                'baja'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW()
);


-- =========================================================
-- 4. DETALLE AGROQUÍMICO
-- =========================================================

CREATE TABLE public.detalle_agroquimico (
    palet_id BIGINT PRIMARY KEY
        REFERENCES public.palet(id)
        ON DELETE CASCADE,

    fecha_elaboracion DATE,

    fecha_vencimiento DATE,

    CHECK (
        fecha_vencimiento IS NULL
        OR fecha_elaboracion IS NULL
        OR fecha_vencimiento >= fecha_elaboracion
    )
);


-- =========================================================
-- 5. DETALLE SEMILLA
-- =========================================================

CREATE TABLE public.detalle_semilla (
    palet_id BIGINT PRIMARY KEY
        REFERENCES public.palet(id)
        ON DELETE CASCADE,

    hibrido VARCHAR(100),

    calibre VARCHAR(50)
);


-- =========================================================
-- 6. MOVIMIENTOS
-- =========================================================
--
-- HISTORIAL INMUTABLE
--
-- Nunca se actualiza.
-- Nunca se elimina.
--
-- corrige_a: si el movimiento es una 'correccion', apunta
-- al movimiento original que está corrigiendo. NULL en
-- cualquier otro caso.
--
-- motivo: obligatorio solo para 'correccion', para dejar
-- registrado por qué se corrigió.
--
-- =========================================================

CREATE TABLE public.movimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    palet_id BIGINT NOT NULL
        REFERENCES public.palet(id)
        ON DELETE RESTRICT,

    usuario_id UUID NOT NULL
        REFERENCES public.usuario(id)
        ON DELETE RESTRICT,

    tipo VARCHAR(20) NOT NULL
        CHECK (
            tipo IN (
                'venta',
                'salida',
                'ajuste',
                'correccion'
            )
        ),

    cantidad NUMERIC(10,2) NOT NULL
        CHECK (
            cantidad > 0
        ),

    corrige_a BIGINT
        REFERENCES public.movimiento(id),

    motivo VARCHAR(255),

    fecha_hora TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    CHECK (
        tipo <> 'correccion' OR motivo IS NOT NULL
    ),

    CHECK (
        tipo = 'correccion' OR corrige_a IS NULL
    )
);


-- =========================================================
-- 7. ÍNDICES
-- =========================================================

CREATE INDEX idx_palet_producto
    ON public.palet(producto_id);

CREATE INDEX idx_palet_estado
    ON public.palet(estado);

CREATE INDEX idx_palet_galpon
    ON public.palet(galpon);

CREATE INDEX idx_palet_lote
    ON public.palet(lote);

CREATE INDEX idx_palet_fecha_ingreso
    ON public.palet(fecha_ingreso);

CREATE INDEX idx_movimiento_palet
    ON public.movimiento(palet_id);

CREATE INDEX idx_movimiento_usuario
    ON public.movimiento(usuario_id);

CREATE INDEX idx_movimiento_fecha
    ON public.movimiento(fecha_hora);

CREATE INDEX idx_movimiento_corrige_a
    ON public.movimiento(corrige_a);


-- =========================================================
-- 8. UPDATED_AT
-- =========================================================

CREATE OR REPLACE FUNCTION public.actualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();

    RETURN NEW;
END;
$$;


CREATE TRIGGER trigger_palet_updated_at
BEFORE UPDATE ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_updated_at();


-- =========================================================
-- 9. FUNCIONES DE AUTORIZACIÓN
-- =========================================================

CREATE OR REPLACE FUNCTION public.usuario_activo()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.usuario
        WHERE id = auth.uid()
        AND activo = TRUE
    );
$$;


CREATE OR REPLACE FUNCTION public.es_operario()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.usuario
        WHERE id = auth.uid()
        AND rol = 'operario'
        AND activo = TRUE
    );
$$;


CREATE OR REPLACE FUNCTION public.es_jefe()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.usuario
        WHERE id = auth.uid()
        AND rol = 'jefe'
        AND activo = TRUE
    );
$$;


-- =========================================================
-- 10. CREAR USUARIO AUTOMÁTICAMENTE
-- =========================================================
--
-- Todo usuario registrado empieza como OPERARIO.
--
-- Para convertirlo en jefe:
--
-- UPDATE public.usuario
-- SET rol = 'jefe'
-- WHERE id = 'UUID';
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.crear_usuario()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN

    INSERT INTO public.usuario (
        id,
        nombre,
        rol,
        activo
    )
    VALUES (
        NEW.id,

        COALESCE(
            NEW.raw_user_meta_data ->> 'nombre',
            NEW.email
        ),

        'operario',

        TRUE
    );

    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_crear_usuario
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.crear_usuario();


-- =========================================================
-- 11. INICIALIZAR PALET
-- =========================================================
--
-- Al crear un palet:
--
-- cantidad_disponible = cantidad_inicial
-- estado = activo
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.inicializar_palet()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    NEW.cantidad_disponible :=
        NEW.cantidad_inicial;

    NEW.estado := 'activo';

    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_inicializar_palet
BEFORE INSERT ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.inicializar_palet();


-- =========================================================
-- 12. PROTEGER DATOS DE STOCK
-- =========================================================
--
-- Impide modificar directamente:
--
--   cantidad_inicial
--   cantidad_disponible
--   estado
--
-- registrar_movimiento() y corregir_movimiento() son los
-- únicos mecanismos autorizados para modificar
-- cantidad_disponible y estado (ambos corren como
-- SECURITY DEFINER, por eso current_user != session_user
-- cuando pasan por acá y no disparan la excepción).
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.proteger_stock_palet()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    IF NEW.cantidad_inicial IS DISTINCT FROM OLD.cantidad_inicial THEN
        RAISE EXCEPTION
            'La cantidad inicial no puede modificarse después de crear el palet';
    END IF;

    IF (
        NEW.cantidad_disponible IS DISTINCT FROM OLD.cantidad_disponible
        OR NEW.estado IS DISTINCT FROM OLD.estado
    )
    AND current_user = session_user THEN

        RAISE EXCEPTION
            'El stock solo puede modificarse mediante registrar_movimiento() o corregir_movimiento()';

    END IF;

    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_proteger_stock_palet
BEFORE UPDATE ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.proteger_stock_palet();


-- =========================================================
-- 12.5. PROTEGER IDENTIDAD DEL PALET
-- =========================================================
--
-- Un palet que ya tiene movimientos no puede cambiar:
--   - producto
--   - lote
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.proteger_identidad_palet()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_categoria_nueva VARCHAR(20);
    v_tiene_movimientos BOOLEAN;
    v_tiene_detalle_agro BOOLEAN;
    v_tiene_detalle_semilla BOOLEAN;
BEGIN

    IF NEW.producto_id IS DISTINCT FROM OLD.producto_id
       OR NEW.lote IS DISTINCT FROM OLD.lote THEN

        SELECT EXISTS (
            SELECT 1
            FROM public.movimiento
            WHERE palet_id = OLD.id
        )
        INTO v_tiene_movimientos;

        IF v_tiene_movimientos THEN
            RAISE EXCEPTION
                'No se puede cambiar producto o lote de un palet que ya tiene movimientos';
        END IF;

    END IF;


    IF NEW.producto_id IS DISTINCT FROM OLD.producto_id THEN

        SELECT categoria
        INTO v_categoria_nueva
        FROM public.producto
        WHERE id = NEW.producto_id;

        IF v_categoria_nueva IS NULL THEN
            RAISE EXCEPTION
                'El producto indicado no existe';
        END IF;


        SELECT EXISTS (
            SELECT 1
            FROM public.detalle_agroquimico
            WHERE palet_id = OLD.id
        )
        INTO v_tiene_detalle_agro;


        SELECT EXISTS (
            SELECT 1
            FROM public.detalle_semilla
            WHERE palet_id = OLD.id
        )
        INTO v_tiene_detalle_semilla;


        IF v_categoria_nueva <> 'agroquimico'
           AND v_tiene_detalle_agro THEN

            RAISE EXCEPTION
                'No se puede cambiar el producto: el palet tiene un detalle agroquímico';

        END IF;


        IF v_categoria_nueva <> 'semilla'
           AND v_tiene_detalle_semilla THEN

            RAISE EXCEPTION
                'No se puede cambiar el producto: el palet tiene un detalle de semilla';

        END IF;

    END IF;


    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_proteger_identidad_palet
BEFORE UPDATE ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.proteger_identidad_palet();


-- =========================================================
-- 13. VALIDAR DETALLE AGROQUÍMICO
-- =========================================================

CREATE OR REPLACE FUNCTION public.validar_detalle_agroquimico()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_categoria VARCHAR(20);
BEGIN

    SELECT p.categoria
    INTO v_categoria
    FROM public.palet pa
    INNER JOIN public.producto p
        ON p.id = pa.producto_id
    WHERE pa.id = NEW.palet_id;


    IF v_categoria IS NULL THEN
        RAISE EXCEPTION
            'El palet no existe';
    END IF;


    IF v_categoria <> 'agroquimico' THEN
        RAISE EXCEPTION
            'El palet no corresponde a un producto agroquímico';
    END IF;


    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_validar_detalle_agroquimico
BEFORE INSERT OR UPDATE ON public.detalle_agroquimico
FOR EACH ROW
EXECUTE FUNCTION public.validar_detalle_agroquimico();


-- =========================================================
-- 14. VALIDAR DETALLE SEMILLA
-- =========================================================

CREATE OR REPLACE FUNCTION public.validar_detalle_semilla()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_categoria VARCHAR(20);
BEGIN

    SELECT p.categoria
    INTO v_categoria
    FROM public.palet pa
    INNER JOIN public.producto p
        ON p.id = pa.producto_id
    WHERE pa.id = NEW.palet_id;


    IF v_categoria IS NULL THEN
        RAISE EXCEPTION
            'El palet no existe';
    END IF;


    IF v_categoria <> 'semilla' THEN
        RAISE EXCEPTION
            'El palet no corresponde a un producto semilla';
    END IF;


    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_validar_detalle_semilla
BEFORE INSERT OR UPDATE ON public.detalle_semilla
FOR EACH ROW
EXECUTE FUNCTION public.validar_detalle_semilla();


-- =========================================================
-- 15. PROTEGER CATEGORÍA DE PRODUCTOS
-- =========================================================
--
-- Una vez que un producto tiene palets asociados,
-- su categoría no puede cambiar.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.proteger_categoria_producto()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    IF NEW.categoria IS DISTINCT FROM OLD.categoria THEN

        IF EXISTS (
            SELECT 1
            FROM public.palet
            WHERE producto_id = OLD.id
        ) THEN

            RAISE EXCEPTION
                'No se puede cambiar la categoría de un producto que ya tiene palets asociados';

        END IF;

    END IF;


    RETURN NEW;

END;
$$;


CREATE TRIGGER trigger_proteger_categoria_producto
BEFORE UPDATE ON public.producto
FOR EACH ROW
EXECUTE FUNCTION public.proteger_categoria_producto();


-- =========================================================
-- 16. REGISTRAR MOVIMIENTO
-- =========================================================
--
-- ESTA FUNCIÓN MODIFICA:
--
--   cantidad_disponible
--   estado
--
-- Además crea el registro histórico.
--
-- Todo ocurre dentro de una única transacción.
--
-- TODOS LOS TIPOS RESTAN STOCK:
--
--   venta  -> resta stock
--   salida -> resta stock
--   ajuste -> resta stock
--
-- Para corregir un error de tipeo (sumar stock), no se usa
-- esta función: se usa corregir_movimiento() (sección 16.5).
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.registrar_movimiento(
    p_palet_id BIGINT,
    p_tipo VARCHAR,
    p_cantidad NUMERIC
)
RETURNS public.movimiento
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$

DECLARE
    v_usuario_id UUID;
    v_palet public.palet%ROWTYPE;
    v_nueva_cantidad NUMERIC;
    v_nuevo_estado VARCHAR(20);
    v_movimiento public.movimiento%ROWTYPE;

BEGIN

    -- =====================================================
    -- 1. Usuario autenticado
    -- =====================================================

    v_usuario_id := auth.uid();

    IF v_usuario_id IS NULL THEN
        RAISE EXCEPTION
            'Usuario no autenticado';
    END IF;


    -- =====================================================
    -- 2. Verificar operario
    -- =====================================================

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION
            'Solo los operarios pueden registrar movimientos';
    END IF;


    -- =====================================================
    -- 3. Validar tipo
    -- =====================================================

    IF p_tipo NOT IN (
        'venta',
        'salida',
        'ajuste'
    ) THEN

        RAISE EXCEPTION
            'Tipo de movimiento inválido';

    END IF;


    -- =====================================================
    -- 4. Validar cantidad
    -- =====================================================

    IF p_cantidad IS NULL
       OR p_cantidad <= 0 THEN

        RAISE EXCEPTION
            'La cantidad debe ser mayor que cero';

    END IF;


    -- =====================================================
    -- 5. Obtener palet y bloquearlo
    -- =====================================================
    --
    -- FOR UPDATE evita problemas si dos operarios
    -- intentan modificar el mismo palet al mismo tiempo.
    --
    -- =====================================================

    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = p_palet_id
    FOR UPDATE;


    IF NOT FOUND THEN
        RAISE EXCEPTION
            'El palet no existe';
    END IF;


    -- =====================================================
    -- 6. Verificar estado
    -- =====================================================

    IF v_palet.estado = 'baja' THEN
        RAISE EXCEPTION
            'El palet se encuentra dado de baja';
    END IF;


    IF v_palet.cantidad_disponible = 0 THEN
        RAISE EXCEPTION
            'El palet no tiene stock disponible';
    END IF;


    -- =====================================================
    -- 7. Verificar stock suficiente
    -- =====================================================

    IF p_cantidad > v_palet.cantidad_disponible THEN

        RAISE EXCEPTION
            'Stock insuficiente. Disponible: %, solicitado: %',
            v_palet.cantidad_disponible,
            p_cantidad;

    END IF;


    -- =====================================================
    -- 8. CALCULAR NUEVO STOCK (siempre se resta)
    -- =====================================================

    v_nueva_cantidad :=
        v_palet.cantidad_disponible - p_cantidad;


    -- =====================================================
    -- 9. DETERMINAR NUEVO ESTADO
    -- =====================================================

    IF v_nueva_cantidad = 0 THEN

        v_nuevo_estado := 'vacio';

    ELSIF v_nueva_cantidad <
          v_palet.cantidad_inicial THEN

        v_nuevo_estado := 'parcial';

    ELSE

        v_nuevo_estado := 'activo';

    END IF;


    -- =====================================================
    -- 10. ACTUALIZAR PALET
    -- =====================================================

    UPDATE public.palet
    SET
        cantidad_disponible = v_nueva_cantidad,
        estado = v_nuevo_estado
    WHERE id = p_palet_id;


    -- =====================================================
    -- 11. CREAR HISTORIAL
    -- =====================================================

    INSERT INTO public.movimiento (
        palet_id,
        usuario_id,
        tipo,
        cantidad
    )
    VALUES (
        p_palet_id,
        v_usuario_id,
        p_tipo,
        p_cantidad
    )
    RETURNING *
    INTO v_movimiento;


    -- =====================================================
    -- 12. DEVOLVER MOVIMIENTO
    -- =====================================================

    RETURN v_movimiento;

END;
$$;


-- =========================================================
-- 16.5. CORREGIR MOVIMIENTO (deshacer un error de tipeo)
-- =========================================================
--
-- Única función que puede sumar stock. No reemplaza ni
-- edita el movimiento original: crea un movimiento nuevo,
-- de tipo 'correccion', que lo compensa. El historial
-- completo queda intacto y auditable.
--
-- Restricciones:
--   - Solo puede corregir el ÚLTIMO movimiento del palet
--     (no cualquiera del historial).
--   - Solo dentro de los 30 minutos posteriores a su carga.
--   - No se puede corregir una corrección.
--   - El motivo es obligatorio (queda guardado en movimiento.motivo).
--
-- El botón "corregir" del front debe llamar únicamente a
-- esta función, nunca insertar un 'ajuste' con signo
-- invertido ni tocar el palet directamente.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.corregir_movimiento(
    p_movimiento_id BIGINT,
    p_motivo VARCHAR
)
RETURNS public.movimiento
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$

DECLARE
    v_usuario_id UUID;
    v_original public.movimiento%ROWTYPE;
    v_ultimo_id BIGINT;
    v_palet public.palet%ROWTYPE;
    v_nueva_cantidad NUMERIC;
    v_nuevo_estado VARCHAR(20);
    v_movimiento public.movimiento%ROWTYPE;

BEGIN

    -- =====================================================
    -- 1. Usuario autenticado y operario
    -- =====================================================

    v_usuario_id := auth.uid();

    IF v_usuario_id IS NULL THEN
        RAISE EXCEPTION
            'Usuario no autenticado';
    END IF;

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION
            'Solo los operarios pueden corregir movimientos';
    END IF;


    -- =====================================================
    -- 2. Validar motivo
    -- =====================================================

    IF p_motivo IS NULL OR btrim(p_motivo) = '' THEN
        RAISE EXCEPTION
            'Es obligatorio indicar el motivo de la corrección';
    END IF;


    -- =====================================================
    -- 3. Obtener el movimiento original
    -- =====================================================

    SELECT *
    INTO v_original
    FROM public.movimiento
    WHERE id = p_movimiento_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'El movimiento no existe';
    END IF;

    IF v_original.tipo = 'correccion' THEN
        RAISE EXCEPTION
            'No se puede corregir una corrección';
    END IF;


    -- =====================================================
    -- 4. Debe ser el ÚLTIMO movimiento de ese palet
    -- =====================================================

    SELECT id
    INTO v_ultimo_id
    FROM public.movimiento
    WHERE palet_id = v_original.palet_id
    ORDER BY fecha_hora DESC
    LIMIT 1;

    IF v_ultimo_id IS DISTINCT FROM p_movimiento_id THEN
        RAISE EXCEPTION
            'Solo se puede corregir el último movimiento registrado en el palet';
    END IF;


    -- =====================================================
    -- 5. Ventana de tiempo: 30 minutos
    -- =====================================================

    IF NOW() - v_original.fecha_hora > INTERVAL '30 minutes' THEN
        RAISE EXCEPTION
            'El movimiento ya no puede corregirse (fuera de plazo)';
    END IF;


    -- =====================================================
    -- 6. Bloquear el palet y recalcular stock
    -- =====================================================

    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = v_original.palet_id
    FOR UPDATE;

    v_nueva_cantidad :=
        v_palet.cantidad_disponible + v_original.cantidad;

    IF v_nueva_cantidad > v_palet.cantidad_inicial THEN
        RAISE EXCEPTION
            'La corrección dejaría el stock por encima de la cantidad inicial del palet';
    END IF;

    IF v_nueva_cantidad = v_palet.cantidad_inicial THEN
        v_nuevo_estado := 'activo';
    ELSIF v_nueva_cantidad = 0 THEN
        v_nuevo_estado := 'vacio';
    ELSE
        v_nuevo_estado := 'parcial';
    END IF;


    -- =====================================================
    -- 7. Actualizar palet
    -- =====================================================

    UPDATE public.palet
    SET
        cantidad_disponible = v_nueva_cantidad,
        estado = v_nuevo_estado
    WHERE id = v_original.palet_id;


    -- =====================================================
    -- 8. Crear el movimiento de corrección
    -- =====================================================

    INSERT INTO public.movimiento (
        palet_id,
        usuario_id,
        tipo,
        cantidad,
        corrige_a,
        motivo
    )
    VALUES (
        v_original.palet_id,
        v_usuario_id,
        'correccion',
        v_original.cantidad,
        p_movimiento_id,
        p_motivo
    )
    RETURNING *
    INTO v_movimiento;


    RETURN v_movimiento;

END;
$$;


-- =========================================================
-- 17. ACTIVAR RLS
-- =========================================================

ALTER TABLE public.usuario
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.producto
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.palet
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.detalle_agroquimico
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.detalle_semilla
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.movimiento
ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 18. USUARIO - POLICIES
-- =========================================================

CREATE POLICY "usuario_select"
ON public.usuario
FOR SELECT
TO authenticated
USING (
    id = auth.uid()
    OR public.es_jefe()
);


-- =========================================================
-- 19. PRODUCTO - POLICIES
-- =========================================================

CREATE POLICY "producto_select"
ON public.producto
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


CREATE POLICY "producto_insert_operario"
ON public.producto
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "producto_update_operario"
ON public.producto
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "producto_delete_operario"
ON public.producto
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 20. PALET - POLICIES
-- =========================================================

CREATE POLICY "palet_select"
ON public.palet
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


CREATE POLICY "palet_insert_operario"
ON public.palet
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "palet_update_operario"
ON public.palet
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "palet_delete_operario"
ON public.palet
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 21. DETALLE AGROQUÍMICO - POLICIES
-- =========================================================

CREATE POLICY "agroquimico_select"
ON public.detalle_agroquimico
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


CREATE POLICY "agroquimico_insert_operario"
ON public.detalle_agroquimico
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "agroquimico_update_operario"
ON public.detalle_agroquimico
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "agroquimico_delete_operario"
ON public.detalle_agroquimico
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 22. DETALLE SEMILLA - POLICIES
-- =========================================================

CREATE POLICY "semilla_select"
ON public.detalle_semilla
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


CREATE POLICY "semilla_insert_operario"
ON public.detalle_semilla
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "semilla_update_operario"
ON public.detalle_semilla
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


CREATE POLICY "semilla_delete_operario"
ON public.detalle_semilla
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 23. MOVIMIENTO - POLICIES
-- =========================================================
--
-- Todos los usuarios activos pueden consultar.
--
-- Nadie puede insertar directamente.
-- Nadie puede modificar.
-- Nadie puede eliminar.
--
-- registrar_movimiento() y corregir_movimiento() son los
-- únicos caminos (ambos SECURITY DEFINER).
--
-- =========================================================

CREATE POLICY "movimiento_select"
ON public.movimiento
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


-- =========================================================
-- 24. PERMISOS DE COLUMNAS DE PALET
-- =========================================================
--
-- El usuario autenticado NO tiene UPDATE general.
--
-- Solo puede modificar:
--
--   producto_id
--   lote
--   galpon
--   sector
--   fecha_ingreso
--
-- cantidad_inicial:
--   nunca
--
-- cantidad_disponible / estado:
--   registrar_movimiento() / corregir_movimiento()
--
-- =========================================================

REVOKE UPDATE
ON public.palet
FROM authenticated;


GRANT UPDATE (
    producto_id,
    lote,
    galpon,
    sector,
    fecha_ingreso
)
ON public.palet
TO authenticated;


-- =========================================================
-- 25. MOVIMIENTO: BLOQUEAR CRUD DIRECTO
-- =========================================================

REVOKE INSERT
ON public.movimiento
FROM authenticated;

REVOKE UPDATE
ON public.movimiento
FROM authenticated;

REVOKE DELETE
ON public.movimiento
FROM authenticated;


-- =========================================================
-- 26. SEGURIDAD DE FUNCIONES SECURITY DEFINER
-- =========================================================

REVOKE ALL
ON FUNCTION public.registrar_movimiento(BIGINT, VARCHAR, NUMERIC)
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.corregir_movimiento(BIGINT, VARCHAR)
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.usuario_activo()
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.es_operario()
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.es_jefe()
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.crear_usuario()
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.proteger_identidad_palet()
FROM PUBLIC;


-- =========================================================
-- 27. EJECUCIÓN DE FUNCIONES
-- =========================================================

GRANT EXECUTE
ON FUNCTION public.registrar_movimiento(
    BIGINT,
    VARCHAR,
    NUMERIC
)
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.corregir_movimiento(
    BIGINT,
    VARCHAR
)
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.usuario_activo()
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.es_operario()
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.es_jefe()
TO authenticated;


-- =========================================================
-- 28. BLOQUEAR FUNCIONES PARA ANÓNIMOS
-- =========================================================

REVOKE EXECUTE
ON FUNCTION public.registrar_movimiento(
    BIGINT,
    VARCHAR,
    NUMERIC
)
FROM anon;


REVOKE EXECUTE
ON FUNCTION public.corregir_movimiento(
    BIGINT,
    VARCHAR
)
FROM anon;


REVOKE EXECUTE
ON FUNCTION public.usuario_activo()
FROM anon;


REVOKE EXECUTE
ON FUNCTION public.es_operario()
FROM anon;


REVOKE EXECUTE
ON FUNCTION public.es_jefe()
FROM anon;


-- =========================================================
-- FIN
-- =========================================================