-- =========================================================
-- AIBAR
-- CLIENTES Y OBSERVACIONES DE PALET
-- =========================================================
--
-- Dos necesidades que aparecieron con el uso real:
--
-- 1. El depósito guarda mercadería de terceros. Hay que
--    poder decir de quién es cada palet, y consultar qué
--    hay de cada cliente.
--
-- 2. A un palet le pasan cosas —bidones pinchados, envases
--    rotos, humedad— y hay que poder anotarlas en cualquier
--    momento, no solo al darlo de alta.
--
-- Las observaciones van como bitácora y no como un campo de
-- texto en `palet`: cada nota queda con quién la escribió y
-- cuándo. Con un campo único, el segundo operario que anota
-- pisa lo que puso el primero y se pierde la historia, que
-- es justamente lo que se quiere conservar.
--
-- =========================================================


-- =========================================================
-- 1. CLIENTES
-- =========================================================
--
-- Solo el nombre: es lo que hace falta para saber de quién
-- es la mercadería. Si más adelante se necesita CUIT o
-- contacto, se suman columnas sin romper nada.
--
-- =========================================================

CREATE TABLE IF NOT EXISTS public.cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- Mismo criterio que en producto: no queremos dos veces el
-- mismo cliente escrito distinto.
CREATE UNIQUE INDEX IF NOT EXISTS cliente_nombre_unico
ON public.cliente (lower(btrim(nombre)));


ALTER TABLE public.cliente
ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS "cliente_select" ON public.cliente;

CREATE POLICY "cliente_select"
ON public.cliente
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


DROP POLICY IF EXISTS "cliente_insert_operario" ON public.cliente;

CREATE POLICY "cliente_insert_operario"
ON public.cliente
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
);


DROP POLICY IF EXISTS "cliente_update_operario" ON public.cliente;

CREATE POLICY "cliente_update_operario"
ON public.cliente
FOR UPDATE
TO authenticated
USING (
    public.es_operario()
)
WITH CHECK (
    public.es_operario()
);


DROP POLICY IF EXISTS "cliente_delete_operario" ON public.cliente;

CREATE POLICY "cliente_delete_operario"
ON public.cliente
FOR DELETE
TO authenticated
USING (
    public.es_operario()
);


-- =========================================================
-- 2. DUEÑO DEL PALET
-- =========================================================
--
-- Nullable a propósito: sin cliente, la mercadería es de
-- AIBAR. Es el caso más común, y obligar a elegir en cada
-- alta sería fricción para nada.
--
-- ON DELETE RESTRICT: no se puede borrar un cliente que
-- todavía tiene mercadería en el depósito.
--
-- =========================================================

ALTER TABLE public.palet
ADD COLUMN IF NOT EXISTS cliente_id BIGINT
    REFERENCES public.cliente(id)
    ON DELETE RESTRICT;


CREATE INDEX IF NOT EXISTS idx_palet_cliente
ON public.palet(cliente_id);


-- El dueño se puede corregir, igual que el galpón o el
-- sector. Sumarlo al GRANT de columnas de la sección 24 del
-- schema original.
GRANT UPDATE (cliente_id)
ON public.palet
TO authenticated;


-- =========================================================
-- 3. OBSERVACIONES
-- =========================================================
--
-- Historial de notas sobre el palet. Inmutables, como los
-- movimientos: si una nota estaba equivocada, se agrega otra
-- aclarándolo. Así la bitácora refleja lo que se supo en
-- cada momento y no se puede reescribir la historia.
--
-- =========================================================

CREATE TABLE IF NOT EXISTS public.observacion_palet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    palet_id BIGINT NOT NULL
        REFERENCES public.palet(id)
        ON DELETE CASCADE,

    usuario_id UUID NOT NULL
        REFERENCES public.usuario(id)
        ON DELETE RESTRICT,

    texto VARCHAR(500) NOT NULL
        CHECK (btrim(texto) <> ''),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_observacion_palet
ON public.observacion_palet(palet_id);


ALTER TABLE public.observacion_palet
ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS "observacion_select" ON public.observacion_palet;

CREATE POLICY "observacion_select"
ON public.observacion_palet
FOR SELECT
TO authenticated
USING (
    public.usuario_activo()
);


-- Solo operarios, y solo a nombre propio: nadie puede dejar
-- una nota firmada por otro.
DROP POLICY IF EXISTS "observacion_insert_operario" ON public.observacion_palet;

CREATE POLICY "observacion_insert_operario"
ON public.observacion_palet
FOR INSERT
TO authenticated
WITH CHECK (
    public.es_operario()
    AND usuario_id = auth.uid()
);


-- Sin policies de UPDATE ni DELETE: las notas no se editan
-- ni se borran.
REVOKE UPDATE, DELETE
ON public.observacion_palet
FROM authenticated;


-- =========================================================
-- 4. ALTA DE PALET CON CLIENTE Y PRIMERA OBSERVACIÓN
-- =========================================================
--
-- Hay que recrear la función porque cambia su firma, y
-- CREATE OR REPLACE no permite agregar parámetros.
--
-- Sigue siendo SECURITY INVOKER: no saltea nada, RLS se
-- aplica igual que antes.
--
-- =========================================================

DROP FUNCTION IF EXISTS public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR
);


CREATE OR REPLACE FUNCTION public.crear_palet_completo(
    p_producto_id BIGINT,
    p_lote VARCHAR,
    p_cantidad_inicial NUMERIC,
    p_galpon SMALLINT,
    p_sector VARCHAR DEFAULT NULL,
    p_fecha_ingreso DATE DEFAULT NULL,

    -- Solo se usan si el producto es agroquímico
    p_fecha_elaboracion DATE DEFAULT NULL,
    p_fecha_vencimiento DATE DEFAULT NULL,

    -- Solo se usan si el producto es semilla
    p_hibrido VARCHAR DEFAULT NULL,
    p_calibre VARCHAR DEFAULT NULL,

    -- NULL = mercadería propia de AIBAR
    p_cliente_id BIGINT DEFAULT NULL,

    -- Primera nota de la bitácora. Opcional.
    p_observacion VARCHAR DEFAULT NULL
)
RETURNS public.palet
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$

DECLARE
    v_categoria VARCHAR(20);
    v_palet public.palet%ROWTYPE;
    v_observacion VARCHAR(500);

BEGIN

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION
            'Solo los operarios pueden dar de alta palets';
    END IF;


    SELECT categoria
    INTO v_categoria
    FROM public.producto
    WHERE id = p_producto_id;

    IF v_categoria IS NULL THEN
        RAISE EXCEPTION
            'El producto indicado no existe';
    END IF;


    IF p_cliente_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM public.cliente WHERE id = p_cliente_id
       ) THEN
        RAISE EXCEPTION
            'El cliente indicado no existe';
    END IF;


    INSERT INTO public.palet (
        producto_id,
        lote,
        cantidad_inicial,
        galpon,
        sector,
        fecha_ingreso,
        cliente_id
    )
    VALUES (
        p_producto_id,
        p_lote,
        p_cantidad_inicial,
        p_galpon,
        NULLIF(btrim(p_sector), ''),
        COALESCE(p_fecha_ingreso, CURRENT_DATE),
        p_cliente_id
    )
    RETURNING *
    INTO v_palet;


    IF v_categoria = 'agroquimico' THEN

        INSERT INTO public.detalle_agroquimico (
            palet_id,
            fecha_elaboracion,
            fecha_vencimiento
        )
        VALUES (
            v_palet.id,
            p_fecha_elaboracion,
            p_fecha_vencimiento
        );

    ELSIF v_categoria = 'semilla' THEN

        INSERT INTO public.detalle_semilla (
            palet_id,
            hibrido,
            calibre
        )
        VALUES (
            v_palet.id,
            NULLIF(btrim(p_hibrido), ''),
            NULLIF(btrim(p_calibre), '')
        );

    ELSE

        RAISE EXCEPTION
            'Categoría de producto desconocida: %',
            v_categoria;

    END IF;


    -- La observación inicial entra en la misma transacción
    -- que el palet: o queda todo, o no queda nada.
    v_observacion := NULLIF(btrim(p_observacion), '');

    IF v_observacion IS NOT NULL THEN

        INSERT INTO public.observacion_palet (
            palet_id,
            usuario_id,
            texto
        )
        VALUES (
            v_palet.id,
            auth.uid(),
            v_observacion
        );

    END IF;


    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = v_palet.id;

    RETURN v_palet;

END;
$$;


REVOKE ALL
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR, BIGINT, VARCHAR
)
FROM PUBLIC;


GRANT EXECUTE
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR, BIGINT, VARCHAR
)
TO authenticated;


REVOKE EXECUTE
ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE,
    DATE, DATE, VARCHAR, VARCHAR, BIGINT, VARCHAR
)
FROM anon;


-- =========================================================
-- 5. VISTAS DE GERENCIA CON CLIENTE
-- =========================================================
--
-- Se recrean para sumar el dueño del palet y la cantidad de
-- observaciones, que es la señal de que algo pasó con ese
-- palet y conviene abrirlo.
--
-- =========================================================

-- CREATE OR REPLACE solo permite AGREGAR columnas al final: cambiar el orden
-- o insertar una en el medio falla con «cannot change name of view column».
-- Como `cliente_id` va junto al resto de la identificación del palet y no
-- colgada al final, hay que soltar la vista y volver a crearla.
DROP VIEW IF EXISTS public.vista_palet_gerencia;


CREATE VIEW public.vista_palet_gerencia
WITH (security_invoker = on)
AS
SELECT
    p.id,
    p.producto_id,
    p.lote,
    p.cantidad_inicial,
    p.cantidad_disponible,
    p.galpon,
    p.sector,
    p.fecha_ingreso,
    p.estado,

    pr.nombre         AS producto_nombre,
    pr.categoria      AS producto_categoria,
    pr.unidad_medida  AS producto_unidad_medida,

    p.cliente_id,
    c.nombre          AS cliente_nombre,

    da.fecha_elaboracion,
    da.fecha_vencimiento,
    ds.hibrido,
    ds.calibre,

    (da.fecha_vencimiento - CURRENT_DATE) AS dias_para_vencer,

    ultimo.fecha_hora AS ultimo_movimiento,

    (CURRENT_DATE - COALESCE(ultimo.fecha_hora::date, p.fecha_ingreso))
        AS dias_sin_movimiento,

    COALESCE(obs.cantidad, 0) AS cantidad_observaciones

FROM public.palet p

INNER JOIN public.producto pr
    ON pr.id = p.producto_id

LEFT JOIN public.cliente c
    ON c.id = p.cliente_id

LEFT JOIN public.detalle_agroquimico da
    ON da.palet_id = p.id

LEFT JOIN public.detalle_semilla ds
    ON ds.palet_id = p.id

LEFT JOIN LATERAL (
    SELECT max(m.fecha_hora) AS fecha_hora
    FROM public.movimiento m
    WHERE m.palet_id = p.id
) ultimo ON TRUE

LEFT JOIN LATERAL (
    SELECT count(*) AS cantidad
    FROM public.observacion_palet o
    WHERE o.palet_id = p.id
) obs ON TRUE;


GRANT SELECT ON public.vista_palet_gerencia TO authenticated;
REVOKE ALL ON public.vista_palet_gerencia FROM anon;


-- =========================================================
-- FIN
-- =========================================================
