-- =========================================================
-- AIBAR
-- TRANSPORTISTAS: QUIÉN TRAJO Y QUIÉN SE LLEVÓ
-- =========================================================
--
-- QUÉ AGREGA
--
-- Hasta ahora el depósito registraba qué entró y qué salió,
-- pero no en manos de quién. Cuando aparece un faltante o
-- una carga mal entregada, «salieron 400 kg el martes» no
-- alcanza: hace falta saber qué camión se los llevó.
--
-- Se suman dos vínculos, y son distintos a propósito:
--
--   palet.transportista_id      QUIÉN LO TRAJO
--     Es un dato del ingreso y no cambia nunca más.
--
--   movimiento.transportista_id QUIÉN SE LO LLEVÓ
--     Va en el movimiento y no en el palet porque un palet
--     sale de a partes: 400 kg con un chofer el martes y 300
--     con otro el jueves. En el palet solo se podría guardar
--     el último, y se perderían los anteriores.
--
-- Los dos son opcionales: si el operario no llegó a
-- preguntar quién era, el alta y la salida no se traban.
--
--
-- LOS DATOS
--
-- Los 43 choferes y las 9 empresas vienen de la base de
-- viajes que ya usa AIBAR. Se importan normalizados:
--
--   - Los nombres venían mezclados ('diego mateo' junto a
--     'DAMIAN ARCURE ') y quedan capitalizados y sin espacios
--     de sobra: 'Diego Mateo', 'Damian Arcure'.
--   - Una empresa traía un espacio duro invisible
--     ('ALLPA<NBSP>SRL') que se normaliza a un espacio común;
--     si no, buscarla escribiendo el nombre no la encontraría.
--   - No se importa el DNI: no hace falta para identificar al
--     chofer en el depósito, y en el origen venía irregular
--     (números de 7 y de 9 dígitos).
--
-- Se puede correr más de una vez sin duplicar: los INSERT
-- van con ON CONFLICT DO NOTHING sobre el nombre.
--
--
-- CÓMO SE CORRE
--
-- En el SQL Editor, entero y de una vez.
--
-- =========================================================

BEGIN;


-- =========================================================
-- 1. LAS EMPRESAS DE TRANSPORTE
-- =========================================================
--
-- Tabla y no un texto suelto en cada chofer, por lo mismo
-- que los sectores: escrita a mano, 'MARCOS RULLO' y 'Marcos
-- Rullo' serían dos transportes distintos para la base y el
-- mismo camión en la calle.
--
-- =========================================================

CREATE TABLE IF NOT EXISTS public.empresa_transporte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL
        CHECK (btrim(nombre) <> ''),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS empresa_transporte_nombre_unico
    ON public.empresa_transporte (upper(btrim(nombre)));


-- =========================================================
-- 2. LOS CHOFERES
-- =========================================================
--
-- `activo` en vez de borrar: un chofer que deja de trabajar
-- tiene palets y movimientos apuntándole, y borrarlo rompería
-- el historial de quién trajo y quién se llevó cada cosa.
--
-- =========================================================

CREATE TABLE IF NOT EXISTS public.transportista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL
        CHECK (btrim(nombre) <> ''),

    /* `null` = fletero por su cuenta, sin transporte detrás. */
    empresa_transporte_id BIGINT
        REFERENCES public.empresa_transporte(id)
        ON DELETE SET NULL,

    telefono VARCHAR(30),

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS transportista_nombre_unico
    ON public.transportista (upper(btrim(nombre)));

CREATE INDEX IF NOT EXISTS transportista_empresa
    ON public.transportista (empresa_transporte_id);


-- =========================================================
-- 3. PERMISOS
-- =========================================================
--
-- Los lee cualquier usuario activo —el jefe también, que ve
-- quién trajo cada palet en el panel— y los crea el operario,
-- que es quien está en la puerta cuando llega un camión con
-- un chofer que no está en la lista.
--
-- =========================================================

ALTER TABLE public.empresa_transporte ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transportista ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS empresa_transporte_select ON public.empresa_transporte;
CREATE POLICY empresa_transporte_select
ON public.empresa_transporte
FOR SELECT
TO authenticated
USING (public.usuario_activo());

DROP POLICY IF EXISTS empresa_transporte_insert_operario ON public.empresa_transporte;
CREATE POLICY empresa_transporte_insert_operario
ON public.empresa_transporte
FOR INSERT
TO authenticated
WITH CHECK (public.es_operario());

DROP POLICY IF EXISTS transportista_select ON public.transportista;
CREATE POLICY transportista_select
ON public.transportista
FOR SELECT
TO authenticated
USING (public.usuario_activo());

DROP POLICY IF EXISTS transportista_insert_operario ON public.transportista;
CREATE POLICY transportista_insert_operario
ON public.transportista
FOR INSERT
TO authenticated
WITH CHECK (public.es_operario());

DROP POLICY IF EXISTS transportista_update_operario ON public.transportista;
CREATE POLICY transportista_update_operario
ON public.transportista
FOR UPDATE
TO authenticated
USING (public.es_operario())
WITH CHECK (public.es_operario());

GRANT SELECT ON public.empresa_transporte TO authenticated;
GRANT INSERT ON public.empresa_transporte TO authenticated;

GRANT SELECT ON public.transportista TO authenticated;
GRANT INSERT ON public.transportista TO authenticated;
GRANT UPDATE (nombre, empresa_transporte_id, telefono, activo)
    ON public.transportista TO authenticated;

GRANT USAGE, SELECT ON SEQUENCE public.empresa_transporte_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.transportista_id_seq TO authenticated;


-- =========================================================
-- 4. LOS DATOS QUE YA EXISTEN
-- =========================================================

INSERT INTO public.empresa_transporte (nombre)
VALUES
    ('AI BAR SRL'),
    ('ANALISIS AGROP.ALLPA SRL'),
    ('CRISTIAN GABRIELI'),
    ('EMP RULLO SEBASTIAN'),
    ('GUILLERO BOYLE'),
    ('JOSUE QUERO'),
    ('LA COTUMA VC'),
    ('MARCOS RULLO'),
    ('PASTORINI')
ON CONFLICT DO NOTHING;


-- Los choferes, con su empresa resuelta por nombre.
INSERT INTO public.transportista (nombre, empresa_transporte_id, telefono)
SELECT
    datos.nombre,
    (SELECT e.id
       FROM public.empresa_transporte e
      WHERE upper(btrim(e.nombre)) = upper(btrim(datos.empresa))),
    datos.telefono
FROM (
VALUES
    ('Alexis Grande', 'AI BAR SRL', '3462318166'),
    ('Andres Medina', 'AI BAR SRL', '3462648300'),
    ('Angel Guerreño', 'JOSUE QUERO', '3462343874'),
    ('Ariel Leguizamon', 'MARCOS RULLO', '3462383722'),
    ('Brian Diaz', 'AI BAR SRL', '3462652222'),
    ('Camilo Finos', 'AI BAR SRL', '3462312358'),
    ('Ceferino Medina', 'LA COTUMA VC', '3462617455'),
    ('Correa Gonzalo', 'AI BAR SRL', '3468588843'),
    ('Damian Arcure', 'PASTORINI', '3468506689'),
    ('Dario Tolosa', 'AI BAR SRL', '3462699731'),
    ('Diego Mateo', 'AI BAR SRL', '3462504163'),
    ('Diego Miño', 'AI BAR SRL', '3462669572'),
    ('Elian Romo', 'GUILLERO BOYLE', '3416145542'),
    ('Enzo Ameri', 'EMP RULLO SEBASTIAN', '3462543660'),
    ('Federico Bainotti', 'AI BAR SRL', '3462419727'),
    ('Francisco Duero', 'AI BAR SRL', '3329628110'),
    ('Franco Grande', 'AI BAR SRL', '3462546129'),
    ('Gabriel Ramirez', 'ANALISIS AGROP.ALLPA SRL', '3462324356'),
    ('Gaston Castillo', 'CRISTIAN GABRIELI', '3462240068'),
    ('Gustavo Bessone', 'LA COTUMA VC', '3462556269'),
    ('Ismael Marquez', 'AI BAR SRL', '346254668'),
    ('Ivan Barrios', 'AI BAR SRL', '3462373812'),
    ('Jose Luis Ferreyra', 'AI BAR SRL', '3462563305'),
    ('Josue Quero', 'JOSUE QUERO', '3462650256'),
    ('Juani Baudino', 'AI BAR SRL', '3462672267'),
    ('Julian Cepeda', 'AI BAR SRL', '3462698567'),
    ('Kevin Horton', 'AI BAR SRL', '3462699731'),
    ('Leandro Aguirre', 'AI BAR SRL', '3462699730'),
    ('Leandro Boasso', 'AI BAR SRL', '3462546668'),
    ('Marcelo Blanco', 'AI BAR SRL', '3462216534'),
    ('Mario Medina', 'GUILLERO BOYLE', '3462599319'),
    ('Matias Leguizamon', 'AI BAR SRL', '3462648300'),
    ('Maximiliano Garcia', 'AI BAR SRL', '3462693458'),
    ('Nicolas Pucheta', 'AI BAR SRL', '3462505117'),
    ('Oscar Gigena', 'AI BAR SRL', '3462547749'),
    ('Ricardo Gonzalez', 'MARCOS RULLO', '346256777'),
    ('Ricardo Odermatt', 'CRISTIAN GABRIELI', '3462415959'),
    ('Ruben Rosales', 'EMP RULLO SEBASTIAN', '3462617852'),
    ('Santiago Armingol', 'AI BAR SRL', '3462620764'),
    ('Sebastian Marciano', 'AI BAR SRL', '3462668439'),
    ('Sevola Osvaldo', 'EMP RULLO SEBASTIAN', '3462620016'),
    ('Sevola Pablo', NULL, '3462627878'),
    ('Victor Gigena', 'AI BAR SRL', '3462536779')
) AS datos(nombre, empresa, telefono)
ON CONFLICT DO NOTHING;


-- =========================================================
-- 5. EL VÍNCULO CON LOS PALETS Y LOS MOVIMIENTOS
-- =========================================================
--
-- ON DELETE SET NULL y no RESTRICT: si alguna vez se borra un
-- chofer, el palet y su historial tienen que seguir
-- existiendo. Se pierde el dato de quién lo trajo, no el
-- palet. Para el caso normal está `activo`, que lo saca de la
-- lista sin tocar nada de lo ya registrado.
--
-- =========================================================

ALTER TABLE public.palet
ADD COLUMN IF NOT EXISTS transportista_id BIGINT
    REFERENCES public.transportista(id)
    ON DELETE SET NULL;

ALTER TABLE public.movimiento
ADD COLUMN IF NOT EXISTS transportista_id BIGINT
    REFERENCES public.transportista(id)
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS palet_transportista ON public.palet (transportista_id);
CREATE INDEX IF NOT EXISTS movimiento_transportista ON public.movimiento (transportista_id);

COMMENT ON COLUMN public.palet.transportista_id IS
    'Quién trajo la mercadería. Dato del ingreso: no cambia.';

COMMENT ON COLUMN public.movimiento.transportista_id IS
    'Quién se llevó la mercadería en esta salida. Va en el movimiento y no en '
    'el palet porque un palet sale de a partes, cada una en un camión distinto.';


-- El operario puede corregir a quién anotó como transportista del palet, igual
-- que corrige el lote o el sector. El stock sigue fuera del GRANT.
GRANT UPDATE (transportista_id) ON public.palet TO authenticated;


-- =========================================================
-- 6. EL ALTA REGISTRA QUIÉN TRAJO
-- =========================================================
--
-- Las dos funciones de alta reciben el chofer y lo guardan en
-- el palet. Opcional: si no vino, va en NULL y el alta sigue
-- funcionando igual que antes.
--
-- =========================================================

DROP FUNCTION IF EXISTS public.crear_palet_completo(
    VARCHAR, NUMERIC, BIGINT, VARCHAR, BIGINT, VARCHAR, VARCHAR,
    DATE, DATE, DATE, BIGINT, VARCHAR
);

CREATE OR REPLACE FUNCTION public.crear_palet_completo(
    p_lote              VARCHAR,
    p_cantidad_inicial  NUMERIC,
    p_sector_id         BIGINT,
    p_unidad_medida     VARCHAR DEFAULT NULL,
    p_producto_id       BIGINT  DEFAULT NULL,
    p_hibrido           VARCHAR DEFAULT NULL,
    p_calibre           VARCHAR DEFAULT NULL,
    p_fecha_ingreso     DATE    DEFAULT NULL,
    p_fecha_elaboracion DATE    DEFAULT NULL,
    p_fecha_vencimiento DATE    DEFAULT NULL,
    p_cliente_id        BIGINT  DEFAULT NULL,
    p_observacion       VARCHAR DEFAULT NULL,
    p_transportista_id  BIGINT  DEFAULT NULL
)
RETURNS public.palet
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
    v_producto_id BIGINT;
    v_categoria   VARCHAR(20);
    v_unidad      VARCHAR(20);
    v_sector      public.sector;
    v_palet       public.palet;
BEGIN

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION 'Solo los operarios pueden dar de alta palets';
    END IF;

    IF p_producto_id IS NULL THEN
        v_producto_id := public.obtener_o_crear_semilla(p_hibrido);
    ELSE
        v_producto_id := p_producto_id;
    END IF;

    SELECT categoria, unidad_medida
      INTO v_categoria, v_unidad
      FROM public.producto
     WHERE id = v_producto_id;

    IF v_categoria IS NULL THEN
        RAISE EXCEPTION 'El producto no existe';
    END IF;

    v_unidad := COALESCE(
        NULLIF(btrim(p_unidad_medida), ''),
        NULLIF(btrim(v_unidad), ''),
        'unidad'
    );

    IF p_sector_id IS NULL THEN
        RAISE EXCEPTION 'Elegí en qué sector queda el palet';
    END IF;

    SELECT * INTO v_sector
      FROM public.sector
     WHERE id = p_sector_id;

    IF v_sector IS NULL THEN
        RAISE EXCEPTION 'El sector indicado no existe';
    END IF;

    IF NOT v_sector.activo THEN
        RAISE EXCEPTION 'El sector % ya no está en uso. Elegí otro.', v_sector.nombre;
    END IF;

    IF p_cliente_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM public.cliente WHERE id = p_cliente_id
       ) THEN
        RAISE EXCEPTION 'El cliente indicado no existe';
    END IF;

    IF p_transportista_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM public.transportista WHERE id = p_transportista_id
       ) THEN
        RAISE EXCEPTION 'El transportista indicado no existe';
    END IF;

    INSERT INTO public.palet (
        producto_id,
        lote,
        cantidad_inicial,
        unidad_medida,
        galpon,
        sector_id,
        fecha_ingreso,
        cliente_id,
        transportista_id
    )
    VALUES (
        v_producto_id,
        p_lote,
        p_cantidad_inicial,
        v_unidad,
        v_sector.galpon,
        p_sector_id,
        COALESCE(p_fecha_ingreso, CURRENT_DATE),
        p_cliente_id,
        p_transportista_id
    )
    RETURNING * INTO v_palet;

    IF v_categoria = 'agroquimico' THEN

        INSERT INTO public.detalle_agroquimico (
            palet_id, fecha_elaboracion, fecha_vencimiento
        )
        VALUES (v_palet.id, p_fecha_elaboracion, p_fecha_vencimiento);

    ELSIF v_categoria = 'semilla' THEN

        INSERT INTO public.detalle_semilla (palet_id, hibrido, calibre)
        VALUES (
            v_palet.id,
            NULLIF(btrim(p_hibrido), ''),
            NULLIF(btrim(p_calibre), '')
        );

    ELSE
        RAISE EXCEPTION 'Categoría de producto desconocida: %', v_categoria;
    END IF;

    IF NULLIF(btrim(p_observacion), '') IS NOT NULL THEN
        INSERT INTO public.observacion_palet (palet_id, usuario_id, texto)
        VALUES (v_palet.id, auth.uid(), btrim(p_observacion));
    END IF;

    RETURN v_palet;

END;
$$;

REVOKE ALL ON FUNCTION public.crear_palet_completo(
    VARCHAR, NUMERIC, BIGINT, VARCHAR, BIGINT, VARCHAR, VARCHAR,
    DATE, DATE, DATE, BIGINT, VARCHAR, BIGINT
) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.crear_palet_completo(
    VARCHAR, NUMERIC, BIGINT, VARCHAR, BIGINT, VARCHAR, VARCHAR,
    DATE, DATE, DATE, BIGINT, VARCHAR, BIGINT
) TO authenticated;


-- ---------------------------------------------------------
-- El alta en lote: un camión trae el lote entero
-- ---------------------------------------------------------

DROP FUNCTION IF EXISTS public.crear_palets_en_lote(
    BIGINT, VARCHAR, NUMERIC, VARCHAR, INTEGER, SMALLINT,
    VARCHAR, VARCHAR, DATE, DATE, DATE, BIGINT, VARCHAR
);

CREATE OR REPLACE FUNCTION public.crear_palets_en_lote(
    p_producto_id       BIGINT,
    p_lote              VARCHAR,
    p_cantidad_total    NUMERIC,
    p_unidad_medida     VARCHAR,
    p_cantidad_palets   INTEGER,
    p_galpon            SMALLINT,
    p_hibrido           VARCHAR DEFAULT NULL,
    p_calibre           VARCHAR DEFAULT NULL,
    p_fecha_ingreso     DATE    DEFAULT NULL,
    p_fecha_elaboracion DATE    DEFAULT NULL,
    p_fecha_vencimiento DATE    DEFAULT NULL,
    p_cliente_id        BIGINT  DEFAULT NULL,
    p_observacion       VARCHAR DEFAULT NULL,
    p_transportista_id  BIGINT  DEFAULT NULL
)
RETURNS SETOF public.palet
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
    v_categoria VARCHAR(20);
    v_unidad    VARCHAR(20);
    v_por_palet NUMERIC(10,2);
    v_ultimo    NUMERIC(10,2);
    v_cantidad  NUMERIC(10,2);
    v_palet     public.palet;
    i           INTEGER;
BEGIN

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION 'Solo los operarios pueden dar de alta palets';
    END IF;

    IF p_cantidad_palets IS NULL OR p_cantidad_palets < 1 THEN
        RAISE EXCEPTION 'Poné cuántos palets trae el lote';
    END IF;

    IF p_cantidad_palets > 50 THEN
        RAISE EXCEPTION
            'Un lote no puede tener más de 50 palets. Vinieron %.',
            p_cantidad_palets;
    END IF;

    SELECT categoria, unidad_medida
      INTO v_categoria, v_unidad
      FROM public.producto
     WHERE id = p_producto_id;

    IF v_categoria IS NULL THEN
        RAISE EXCEPTION 'El producto no existe';
    END IF;

    v_unidad := COALESCE(
        NULLIF(btrim(p_unidad_medida), ''),
        NULLIF(btrim(v_unidad), ''),
        'unidad'
    );

    IF p_cliente_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM public.cliente WHERE id = p_cliente_id
       ) THEN
        RAISE EXCEPTION 'El cliente indicado no existe';
    END IF;

    IF p_transportista_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM public.transportista WHERE id = p_transportista_id
       ) THEN
        RAISE EXCEPTION 'El transportista indicado no existe';
    END IF;

    IF p_cantidad_total IS NULL OR p_cantidad_total <= 0 THEN
        RAISE EXCEPTION 'La cantidad total tiene que ser mayor que cero';
    END IF;

    v_por_palet := trunc(p_cantidad_total / p_cantidad_palets, 2);

    IF v_por_palet <= 0 THEN
        RAISE EXCEPTION
            'No alcanza para % palets: a cada uno le tocaría menos de 0,01 %s',
            p_cantidad_palets, v_unidad;
    END IF;

    v_ultimo := p_cantidad_total - (v_por_palet * (p_cantidad_palets - 1));

    FOR i IN 1..p_cantidad_palets LOOP

        v_cantidad := CASE
            WHEN i = p_cantidad_palets THEN v_ultimo
            ELSE v_por_palet
        END;

        INSERT INTO public.palet (
            producto_id,
            lote,
            cantidad_inicial,
            unidad_medida,
            galpon,
            sector_id,
            fecha_ingreso,
            cliente_id,
            transportista_id
        )
        VALUES (
            p_producto_id,
            p_lote,
            v_cantidad,
            v_unidad,
            p_galpon,
            NULL,
            COALESCE(p_fecha_ingreso, CURRENT_DATE),
            p_cliente_id,
            p_transportista_id
        )
        RETURNING * INTO v_palet;

        IF v_categoria = 'agroquimico' THEN

            INSERT INTO public.detalle_agroquimico (
                palet_id, fecha_elaboracion, fecha_vencimiento
            )
            VALUES (v_palet.id, p_fecha_elaboracion, p_fecha_vencimiento);

        ELSIF v_categoria = 'semilla' THEN

            INSERT INTO public.detalle_semilla (palet_id, hibrido, calibre)
            VALUES (
                v_palet.id,
                NULLIF(btrim(p_hibrido), ''),
                NULLIF(btrim(p_calibre), '')
            );

        ELSE
            RAISE EXCEPTION 'Categoría de producto desconocida: %', v_categoria;
        END IF;

        IF NULLIF(btrim(p_observacion), '') IS NOT NULL THEN
            INSERT INTO public.observacion_palet (palet_id, usuario_id, texto)
            VALUES (v_palet.id, auth.uid(), btrim(p_observacion));
        END IF;

        RETURN NEXT v_palet;

    END LOOP;

    RETURN;

END;
$$;

REVOKE ALL ON FUNCTION public.crear_palets_en_lote(
    BIGINT, VARCHAR, NUMERIC, VARCHAR, INTEGER, SMALLINT,
    VARCHAR, VARCHAR, DATE, DATE, DATE, BIGINT, VARCHAR, BIGINT
) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.crear_palets_en_lote(
    BIGINT, VARCHAR, NUMERIC, VARCHAR, INTEGER, SMALLINT,
    VARCHAR, VARCHAR, DATE, DATE, DATE, BIGINT, VARCHAR, BIGINT
) TO authenticated;


-- =========================================================
-- 7. LA SALIDA REGISTRA QUIÉN SE LA LLEVÓ
-- =========================================================
--
-- Es la misma función de siempre con un parámetro más. Toda
-- la lógica de stock —el bloqueo FOR UPDATE, el chequeo de
-- disponible, el cálculo del estado— queda **exactamente
-- igual**: acá solo se suma a quién se le entregó.
--
-- El chofer se guarda solo en venta y salida. En un ajuste no
-- hay camión: es una rotura, un derrame o un recuento que no
-- cuadra, y anotar un transportista ahí sería inventar que
-- alguien se llevó algo.
--
-- Sigue siendo SECURITY DEFINER porque necesita saltear el
-- trigger `proteger_stock_palet()`, que es lo que impide
-- tocar el stock desde el cliente.
--
-- =========================================================

DROP FUNCTION IF EXISTS public.registrar_movimiento(BIGINT, VARCHAR, NUMERIC);

CREATE OR REPLACE FUNCTION public.registrar_movimiento(
    p_palet_id         BIGINT,
    p_tipo             VARCHAR,
    p_cantidad         NUMERIC,
    p_transportista_id BIGINT DEFAULT NULL
)
RETURNS public.movimiento
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$

DECLARE
    v_usuario_id UUID;
    v_palet public.palet%ROWTYPE;
    v_nueva_cantidad NUMERIC;
    v_nuevo_estado VARCHAR(20);
    v_movimiento public.movimiento%ROWTYPE;
    v_transportista_id BIGINT;

BEGIN

    v_usuario_id := auth.uid();

    IF v_usuario_id IS NULL THEN
        RAISE EXCEPTION 'Usuario no autenticado';
    END IF;

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION 'Solo los operarios pueden registrar movimientos';
    END IF;

    IF p_tipo NOT IN ('venta', 'salida', 'ajuste') THEN
        RAISE EXCEPTION 'Tipo de movimiento inválido';
    END IF;

    IF p_cantidad IS NULL OR p_cantidad <= 0 THEN
        RAISE EXCEPTION 'La cantidad debe ser mayor que cero';
    END IF;

    -- ----- Quién se la lleva -----
    --
    -- En un ajuste se descarta aunque venga: no hubo ningún
    -- camión, y dejarlo pasar mancharía el historial con
    -- entregas que no existieron.
    v_transportista_id := CASE
        WHEN p_tipo IN ('venta', 'salida') THEN p_transportista_id
        ELSE NULL
    END;

    IF v_transportista_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM public.transportista WHERE id = v_transportista_id
       ) THEN
        RAISE EXCEPTION 'El transportista indicado no existe';
    END IF;

    -- FOR UPDATE: si dos operarios descuentan del mismo palet a la vez, el
    -- segundo espera y ve el stock ya actualizado.
    SELECT *
    INTO v_palet
    FROM public.palet
    WHERE id = p_palet_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'El palet no existe';
    END IF;

    IF v_palet.estado = 'baja' THEN
        RAISE EXCEPTION 'El palet se encuentra dado de baja';
    END IF;

    IF v_palet.cantidad_disponible = 0 THEN
        RAISE EXCEPTION 'El palet no tiene stock disponible';
    END IF;

    IF p_cantidad > v_palet.cantidad_disponible THEN
        RAISE EXCEPTION
            'Stock insuficiente. Disponible: %, solicitado: %',
            v_palet.cantidad_disponible,
            p_cantidad;
    END IF;

    v_nueva_cantidad := v_palet.cantidad_disponible - p_cantidad;

    IF v_nueva_cantidad = 0 THEN
        v_nuevo_estado := 'vacio';
    ELSIF v_nueva_cantidad < v_palet.cantidad_inicial THEN
        v_nuevo_estado := 'parcial';
    ELSE
        v_nuevo_estado := 'activo';
    END IF;

    UPDATE public.palet
    SET cantidad_disponible = v_nueva_cantidad,
        estado = v_nuevo_estado
    WHERE id = p_palet_id;

    INSERT INTO public.movimiento (
        palet_id,
        usuario_id,
        tipo,
        cantidad,
        transportista_id
    )
    VALUES (
        p_palet_id,
        v_usuario_id,
        p_tipo,
        p_cantidad,
        v_transportista_id
    )
    RETURNING *
    INTO v_movimiento;

    RETURN v_movimiento;

END;
$$;

REVOKE ALL ON FUNCTION public.registrar_movimiento(BIGINT, VARCHAR, NUMERIC, BIGINT)
    FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.registrar_movimiento(BIGINT, VARCHAR, NUMERIC, BIGINT)
    TO authenticated;


-- =========================================================
-- 8. EL PANEL VE QUIÉN TRAJO CADA PALET
-- =========================================================
--
-- ⚠️ `security_invoker = on`: sin eso la vista correría con
-- los permisos de quien la creó y saltearía RLS por completo.
--
-- =========================================================

DROP VIEW IF EXISTS public.vista_palet_gerencia;

CREATE VIEW public.vista_palet_gerencia
WITH (security_invoker = on)
AS
SELECT
    p.id,
    p.producto_id,
    p.lote,
    p.cantidad_inicial,
    p.cantidad_disponible,
    p.unidad_medida,
    p.galpon,
    p.sector,
    p.fecha_ingreso,
    p.estado,

    pr.nombre           AS producto_nombre,
    pr.categoria        AS producto_categoria,
    pr.marca            AS producto_marca,
    pr.principio_activo AS producto_principio_activo,
    pr.concentracion    AS producto_concentracion,

    p.cliente_id,
    c.nombre            AS cliente_nombre,

    p.transportista_id,
    t.nombre            AS transportista_nombre,

    da.fecha_elaboracion,
    da.fecha_vencimiento,
    ds.hibrido,
    ds.calibre,

    (da.fecha_vencimiento - CURRENT_DATE) AS dias_para_vencer,

    ultimo.fecha_hora AS ultimo_movimiento,

    (CURRENT_DATE - COALESCE(ultimo.fecha_hora::date, p.fecha_ingreso))
        AS dias_sin_movimiento,

    COALESCE(obs.cantidad, 0) AS cantidad_observaciones,

    ultima_obs.texto      AS ultima_observacion,
    ultima_obs.created_at AS ultima_observacion_fecha,
    ultima_obs.autor      AS ultima_observacion_autor

FROM public.palet p

INNER JOIN public.producto pr
    ON pr.id = p.producto_id

LEFT JOIN public.cliente c
    ON c.id = p.cliente_id

LEFT JOIN public.transportista t
    ON t.id = p.transportista_id

LEFT JOIN public.detalle_agroquimico da
    ON da.palet_id = p.id

LEFT JOIN public.detalle_semilla ds
    ON ds.palet_id = p.id

LEFT JOIN LATERAL (
    SELECT max(m.fecha_hora) AS fecha_hora
    FROM public.movimiento m
    WHERE m.palet_id = p.id
) ultimo ON TRUE

LEFT JOIN LATERAL (
    SELECT count(*) AS cantidad
    FROM public.observacion_palet o
    WHERE o.palet_id = p.id
) obs ON TRUE

LEFT JOIN LATERAL (
    SELECT o.texto, o.created_at, u.nombre AS autor
    FROM public.observacion_palet o
    LEFT JOIN public.usuario u ON u.id = o.usuario_id
    WHERE o.palet_id = p.id
    ORDER BY o.created_at DESC, o.id DESC
    LIMIT 1
) ultima_obs ON TRUE;

GRANT SELECT ON public.vista_palet_gerencia TO authenticated;
REVOKE ALL ON public.vista_palet_gerencia FROM anon;


COMMIT;


-- =========================================================
-- FIN
-- =========================================================
