-- =========================================================
-- AIBAR
-- LOS SECTORES PASAN A SER LUGARES DE VERDAD
-- =========================================================
--
-- QUÉ CAMBIA
--
-- Hasta ahora el sector era texto libre escrito a mano en
-- cada alta. Eso trajo dos problemas:
--
-- 1. Dos palets podían quedar en el mismo lugar físico, que
--    es imposible: en un sector entra un palet y no dos.
--
-- 2. 'A7', 'A-7', 'a7' y ' A7 ' eran cuatro lugares distintos
--    para la base y el mismo estante en el galpón. El palet
--    aparecía «ubicado» en un sector que nadie más iba a
--    encontrar buscando.
--
-- Ahora los sectores son filas de una tabla. Al dar de alta
-- se elige uno de la lista de los que están libres, así que
-- no hay nada que tipear y las dos cosas dejan de poder pasar.
--
--
-- QUÉ PASA CON LOS PALETS QUE YA ESTÁN
--
-- Los sectores que ya se escribieron se convierten en
-- sectores reales y cada palet queda apuntando al suyo: no se
-- pierde ninguna ubicación.
--
-- Si dos palets comparten lugar, el más nuevo queda SIN
-- UBICAR y aparece marcado en la app para que le asignes el
-- sector real. No se elige por vos cuál está bien, porque eso
-- solo se sabe mirando el galpón.
--
--
-- CÓMO SE CORRE
--
-- En el SQL Editor, entero y de una vez. Va en una
-- transacción: si algo falla, no queda nada a medias.
--
-- =========================================================

BEGIN;


-- =========================================================
-- 1. LOS SECTORES
-- =========================================================
--
-- Un sector pertenece a un galpón: el 'A7' del galpón 1 y el
-- 'A7' del galpón 2 son dos lugares distintos, y por eso la
-- unicidad es por (galpón, nombre) y no por nombre solo.
--
-- `activo` en vez de borrar: un sector que se deja de usar
-- —se desarmó la estantería, se cambió la distribución— tiene
-- palets viejos apuntándole, y borrarlo rompería el historial
-- de dónde estuvo cada cosa.
--
-- =========================================================

CREATE TABLE IF NOT EXISTS public.sector (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    galpon SMALLINT NOT NULL
        CHECK (galpon IN (1, 2, 3)),

    nombre VARCHAR(50) NOT NULL
        CHECK (btrim(nombre) <> ''),

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Sin distinguir mayúsculas ni espacios de más: 'A7', 'a7' y
-- ' A7 ' son el mismo estante, y dejar que convivan sería
-- reponer el problema que esta migración viene a resolver.
CREATE UNIQUE INDEX IF NOT EXISTS sector_nombre_unico_por_galpon
    ON public.sector (galpon, upper(btrim(nombre)));

CREATE INDEX IF NOT EXISTS sector_galpon_activo
    ON public.sector (galpon, activo);


-- =========================================================
-- 2. QUIÉN PUEDE VER Y TOCAR LOS SECTORES
-- =========================================================
--
-- Los crea el operario, igual que productos y clientes: si
-- llega mercadería y el lugar donde la ponen no está cargado,
-- tiene que poder cargarlo en el momento. Esperar a que
-- alguien se lo habilite lo deja con el palet en la mano.
--
-- Nadie los borra: se desactivan.
--
-- =========================================================

ALTER TABLE public.sector ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sector_select ON public.sector;
CREATE POLICY sector_select
    ON public.sector
    FOR SELECT
    TO authenticated
    USING (public.usuario_activo());

DROP POLICY IF EXISTS sector_insert_operario ON public.sector;
CREATE POLICY sector_insert_operario
    ON public.sector
    FOR INSERT
    TO authenticated
    WITH CHECK (public.es_operario());

DROP POLICY IF EXISTS sector_update_operario ON public.sector;
CREATE POLICY sector_update_operario
    ON public.sector
    FOR UPDATE
    TO authenticated
    USING (public.es_operario())
    WITH CHECK (public.es_operario());

REVOKE ALL ON public.sector FROM anon;
GRANT SELECT ON public.sector TO authenticated;
GRANT INSERT (galpon, nombre) ON public.sector TO authenticated;
GRANT UPDATE (nombre, activo) ON public.sector TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.sector_id_seq TO authenticated;


-- =========================================================
-- 3. EL PALET APUNTA A SU SECTOR
-- =========================================================
--
-- `sector_id` admite NULL a propósito, y significa una sola
-- cosa: «este palet está en algún lado que todavía no se
-- registró». Es el estado en que quedan los conflictos que
-- resuelve la sección 4, y la app lo muestra marcado para
-- corregirlo.
--
-- No es una puerta abierta para dar de alta sin ubicación:
-- `crear_palet_completo()` lo exige, y ese es el único camino
-- para crear un palet.
--
-- ON DELETE RESTRICT: un sector con palets no se puede
-- borrar. Para eso está `activo`.
--
-- =========================================================

ALTER TABLE public.palet
ADD COLUMN IF NOT EXISTS sector_id BIGINT
    REFERENCES public.sector(id)
    ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS palet_sector_id ON public.palet (sector_id);


-- =========================================================
-- 4. MIGRAR LO QUE YA ESTÁ CARGADO
-- =========================================================
--
-- Primero se crean los sectores que ya se venían escribiendo,
-- unificando las variantes de mayúsculas y espacios. Se toma
-- la forma más usada de cada uno como nombre oficial.
--
-- =========================================================

WITH escrituras AS (
    -- Cada forma en que se escribió cada sector, con cuántas
    -- veces aparece.
    SELECT p.galpon,
           upper(btrim(p.sector)) AS clave,
           btrim(p.sector)        AS nombre,
           count(*)               AS veces
      FROM public.palet p
     WHERE p.sector IS NOT NULL
       AND btrim(p.sector) <> ''
     GROUP BY p.galpon, upper(btrim(p.sector)), btrim(p.sector)
),
elegidas AS (
    -- De todas las variantes del mismo lugar ('A2', 'a2 '), se
    -- queda la más usada: es la que el depósito escribe.
    SELECT galpon,
           nombre,
           row_number() OVER (
               PARTITION BY galpon, clave
               -- Con la misma frecuencia gana la forma con
               -- mayúsculas: COLLATE "C" ordena por byte y 'A2'
               -- va antes que 'a2'. Es la escritura formal.
               ORDER BY veces DESC, nombre COLLATE "C"
           ) AS orden
      FROM escrituras
)
INSERT INTO public.sector (galpon, nombre)
SELECT e.galpon, e.nombre
  FROM elegidas e
 WHERE e.orden = 1
   AND NOT EXISTS (
       SELECT 1
         FROM public.sector s
        WHERE s.galpon = e.galpon
          AND upper(btrim(s.nombre)) = upper(btrim(e.nombre))
   );

-- Cada palet queda apuntando al sector que le corresponde.
UPDATE public.palet p
   SET sector_id = s.id
  FROM public.sector s
 WHERE s.galpon = p.galpon
   AND upper(btrim(s.nombre)) = upper(btrim(p.sector))
   AND p.sector IS NOT NULL
   AND p.sector_id IS NULL;


-- ---------------------------------------------------------
-- Los conflictos: dos palets ocupando el mismo lugar
-- ---------------------------------------------------------
--
-- Se conserva el más viejo, que es el que ya estaba ahí, y el
-- más nuevo queda sin ubicar. Es una decisión arbitraria y
-- por eso NO se descarta el dato: el sector que decía queda
-- anotado en la bitácora del palet, así se puede reconstruir
-- qué pasó parado frente al estante.

WITH conflictos AS (
    SELECT id,
           sector_id,
           sector,
           row_number() OVER (
               PARTITION BY sector_id
               ORDER BY id
           ) AS orden
      FROM public.palet
     WHERE sector_id IS NOT NULL
       AND estado IN ('activo', 'parcial')
),
desalojados AS (
    SELECT id, sector
      FROM conflictos
     WHERE orden > 1
)
INSERT INTO public.observacion_palet (palet_id, usuario_id, texto)
SELECT d.id,
       (SELECT u.id FROM public.usuario u WHERE u.rol = 'jefe' AND u.activo ORDER BY u.id LIMIT 1),
       format(
           'Quedó SIN UBICAR al ordenar los sectores: el sector "%s" ya estaba ocupado por otro palet. Asignale el lugar real donde está.',
           d.sector
       )
  FROM desalojados d
 WHERE EXISTS (SELECT 1 FROM public.usuario WHERE rol = 'jefe' AND activo);

WITH conflictos AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY sector_id
               ORDER BY id
           ) AS orden
      FROM public.palet
     WHERE sector_id IS NOT NULL
       AND estado IN ('activo', 'parcial')
)
UPDATE public.palet
   SET sector_id = NULL,
       sector    = NULL
 WHERE id IN (SELECT id FROM conflictos WHERE orden > 1);


-- =========================================================
-- 5. UN SOLO PALET POR SECTOR
-- =========================================================
--
-- Un índice único parcial, y no un chequeo en la app: dos
-- operarios dando de alta al mismo tiempo desde dos teléfonos
-- se colarían por la ventana que deja cualquier «consultar y
-- después insertar». Acá lo decide la base, que es la única
-- que ve las dos operaciones a la vez.
--
-- El WHERE por estado es lo que hace que el lugar se libere
-- solo: cuando el palet se termina —el trigger lo pasa a
-- 'vacio'— o se da de baja, sale del índice y el sector queda
-- disponible sin que nadie tenga que hacer nada.
--
-- =========================================================

DROP INDEX IF EXISTS public.palet_sector_ocupado_unico;

CREATE UNIQUE INDEX palet_sector_ocupado_unico
    ON public.palet (sector_id)
    WHERE sector_id IS NOT NULL
      AND estado IN ('activo', 'parcial');


-- =========================================================
-- 6. EL GALPÓN Y EL NOMBRE SE DERIVAN DEL SECTOR
-- =========================================================
--
-- `palet.galpon` y `palet.sector` se mantienen, pero dejan de
-- escribirse a mano: los completa este trigger a partir del
-- sector elegido. Son una copia que la base mantiene sola.
--
-- Se conservan en vez de borrarlas porque toda la app las usa
-- —la búsqueda por sector, las vistas del panel, el detalle—
-- y porque un palet sin ubicar necesita igual decir en qué
-- galpón estaba. La integridad la garantiza `sector_id`; esto
-- es solo comodidad de lectura.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.sincronizar_ubicacion_palet()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_sector public.sector;
BEGIN

    IF NEW.sector_id IS NULL THEN
        -- Sin ubicación registrada. El galpón se deja como
        -- está: es el último lugar donde se supo que estuvo.
        NEW.sector := NULL;
        RETURN NEW;
    END IF;

    SELECT * INTO v_sector
      FROM public.sector
     WHERE id = NEW.sector_id;

    IF v_sector IS NULL THEN
        RAISE EXCEPTION 'El sector indicado no existe';
    END IF;

    NEW.galpon := v_sector.galpon;
    NEW.sector := btrim(v_sector.nombre);

    RETURN NEW;

END;
$$;

DROP TRIGGER IF EXISTS trigger_a_sincronizar_ubicacion ON public.palet;

-- El nombre empieza con «a_» a propósito: Postgres dispara
-- los triggers por orden alfabético y este tiene que correr
-- antes que el que valida.
CREATE TRIGGER trigger_a_sincronizar_ubicacion
BEFORE INSERT OR UPDATE OF sector_id ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.sincronizar_ubicacion_palet();

-- Los palets migrados en la sección 4 se asignaron antes de que este trigger
-- existiera, así que conservan el texto tal como se había tipeado ('a2' donde
-- el sector oficial quedó 'A2'). Se normalizan ahora, o quedarían dos nombres
-- para el mismo lugar: justo lo que esta migración viene a terminar.
UPDATE public.palet p
   SET sector = btrim(s.nombre),
       galpon = s.galpon
  FROM public.sector s
 WHERE s.id = p.sector_id
   AND (p.sector IS DISTINCT FROM btrim(s.nombre) OR p.galpon IS DISTINCT FROM s.galpon);


-- =========================================================
-- 7. UN MENSAJE QUE SE ENTIENDA
-- =========================================================
--
-- Sin esto el operario recibe el error crudo de Postgres
-- («duplicate key value violates unique constraint…»), que no
-- dice ni qué sector ni qué palet lo está ocupando.
--
-- No reemplaza al índice: es solo para el mensaje. La
-- garantía sigue siendo el índice, que es el que aguanta dos
-- altas simultáneas.
--
-- =========================================================

CREATE OR REPLACE FUNCTION public.verificar_sector_libre()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_ocupante BIGINT;
    v_nombre   VARCHAR(50);
    v_galpon   SMALLINT;
BEGIN

    IF NEW.sector_id IS NULL OR NEW.estado NOT IN ('activo', 'parcial') THEN
        RETURN NEW;
    END IF;

    SELECT p.id INTO v_ocupante
      FROM public.palet p
     WHERE p.sector_id = NEW.sector_id
       AND p.estado IN ('activo', 'parcial')
       AND p.id IS DISTINCT FROM NEW.id
     LIMIT 1;

    IF v_ocupante IS NOT NULL THEN
        SELECT nombre, galpon INTO v_nombre, v_galpon
          FROM public.sector WHERE id = NEW.sector_id;

        RAISE EXCEPTION
            'El sector % del galpón % ya está ocupado por el palet %. Elegí otro sector o esperá a que ese palet se termine.',
            v_nombre, v_galpon, v_ocupante;
    END IF;

    RETURN NEW;

END;
$$;

DROP TRIGGER IF EXISTS trigger_verificar_sector_libre ON public.palet;

CREATE TRIGGER trigger_verificar_sector_libre
BEFORE INSERT OR UPDATE OF sector_id, estado ON public.palet
FOR EACH ROW
EXECUTE FUNCTION public.verificar_sector_libre();


-- =========================================================
-- 8. EL CLIENTE YA NO ESCRIBE LA UBICACIÓN A MANO
-- =========================================================
--
-- Se cambia el permiso: en vez de `galpon` y `sector`, ahora
-- se actualiza `sector_id`. Mover un palet es elegirle otro
-- sector, y el galpón viaja con él.
--
-- =========================================================

REVOKE UPDATE ON public.palet FROM authenticated;

-- Las mismas columnas que ya estaban permitidas, con `sector_id` en lugar de
-- `galpon` y `sector`: esas dos las escribe ahora el trigger de la sección 6.
GRANT UPDATE (
    producto_id,
    lote,
    sector_id,
    fecha_ingreso,
    cliente_id
) ON public.palet TO authenticated;


-- =========================================================
-- 9. QUÉ SECTORES ESTÁN LIBRES
-- =========================================================
--
-- Es lo que la app necesita para ofrecer la lista al dar de
-- alta. Se resuelve en la base y no en el cliente: si el
-- navegador cruzara sectores contra palets, cada alta tendría
-- que bajarse el depósito entero.
--
-- ⚠️ security_invoker: sin esto la vista correría con los
-- permisos de quien la creó y saltearía RLS por completo.
--
-- =========================================================

DROP VIEW IF EXISTS public.vista_sector_disponible;

CREATE VIEW public.vista_sector_disponible
WITH (security_invoker = on)
AS
SELECT s.id,
       s.galpon,
       s.nombre,
       s.activo,
       p.id       AS palet_id,
       p.lote     AS palet_lote,
       (p.id IS NULL) AS libre
  FROM public.sector s
  LEFT JOIN public.palet p
    ON p.sector_id = s.id
   AND p.estado IN ('activo', 'parcial');

GRANT SELECT ON public.vista_sector_disponible TO authenticated;
REVOKE ALL ON public.vista_sector_disponible FROM anon;


-- =========================================================
-- 10. EL ALTA PIDE UN SECTOR DE LA LISTA
-- =========================================================
--
-- Cambia la firma: antes recibía el galpón y el sector como
-- texto; ahora recibe el id del sector, del que salen los
-- dos. Se elimina la versión vieja para que no queden dos
-- caminos, uno de ellos sin las garantías nuevas.
--
-- =========================================================

DROP FUNCTION IF EXISTS public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, SMALLINT, VARCHAR, DATE, DATE, DATE,
    VARCHAR, VARCHAR, BIGINT, VARCHAR
);

CREATE OR REPLACE FUNCTION public.crear_palet_completo(
    p_producto_id       BIGINT,
    p_lote              VARCHAR,
    p_cantidad_inicial  NUMERIC,
    p_sector_id         BIGINT,
    p_fecha_ingreso     DATE    DEFAULT NULL,
    p_fecha_elaboracion DATE    DEFAULT NULL,
    p_fecha_vencimiento DATE    DEFAULT NULL,
    p_hibrido           VARCHAR DEFAULT NULL,
    p_calibre           VARCHAR DEFAULT NULL,
    p_cliente_id        BIGINT  DEFAULT NULL,
    p_observacion       VARCHAR DEFAULT NULL
)
RETURNS public.palet
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
    v_categoria VARCHAR(20);
    v_sector    public.sector;
    v_palet     public.palet;
BEGIN

    IF NOT public.es_operario() THEN
        RAISE EXCEPTION 'Solo los operarios pueden dar de alta palets';
    END IF;

    IF p_sector_id IS NULL THEN
        RAISE EXCEPTION 'Elegí en qué sector queda el palet';
    END IF;

    SELECT * INTO v_sector
      FROM public.sector
     WHERE id = p_sector_id;

    IF v_sector IS NULL THEN
        RAISE EXCEPTION 'El sector indicado no existe';
    END IF;

    IF NOT v_sector.activo THEN
        RAISE EXCEPTION 'El sector % ya no está en uso. Elegí otro.', v_sector.nombre;
    END IF;

    SELECT categoria
      INTO v_categoria
      FROM public.producto
     WHERE id = p_producto_id;

    IF v_categoria IS NULL THEN
        RAISE EXCEPTION 'El producto no existe';
    END IF;

    IF p_cliente_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM public.cliente WHERE id = p_cliente_id
       ) THEN
        RAISE EXCEPTION 'El cliente indicado no existe';
    END IF;

    -- `galpon` y `sector` los completa el trigger de la
    -- sección 6 a partir de `sector_id`. Se manda el galpón
    -- porque la columna es NOT NULL y el trigger corre
    -- después de que Postgres arma la fila.
    INSERT INTO public.palet (
        producto_id,
        lote,
        cantidad_inicial,
        galpon,
        sector_id,
        fecha_ingreso,
        cliente_id
    )
    VALUES (
        p_producto_id,
        p_lote,
        p_cantidad_inicial,
        v_sector.galpon,
        p_sector_id,
        COALESCE(p_fecha_ingreso, CURRENT_DATE),
        p_cliente_id
    )
    RETURNING * INTO v_palet;

    IF v_categoria = 'agroquimico' THEN

        INSERT INTO public.detalle_agroquimico (
            palet_id,
            fecha_elaboracion,
            fecha_vencimiento
        )
        VALUES (
            v_palet.id,
            p_fecha_elaboracion,
            p_fecha_vencimiento
        );

    ELSIF v_categoria = 'semilla' THEN

        INSERT INTO public.detalle_semilla (
            palet_id,
            hibrido,
            calibre
        )
        VALUES (
            v_palet.id,
            NULLIF(btrim(p_hibrido), ''),
            NULLIF(btrim(p_calibre), '')
        );

    ELSE
        RAISE EXCEPTION 'Categoría de producto desconocida: %', v_categoria;
    END IF;

    IF NULLIF(btrim(p_observacion), '') IS NOT NULL THEN
        INSERT INTO public.observacion_palet (palet_id, usuario_id, texto)
        VALUES (v_palet.id, auth.uid(), btrim(p_observacion));
    END IF;

    RETURN v_palet;

END;
$$;

REVOKE ALL ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, BIGINT, DATE, DATE, DATE,
    VARCHAR, VARCHAR, BIGINT, VARCHAR
) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.crear_palet_completo(
    BIGINT, VARCHAR, NUMERIC, BIGINT, DATE, DATE, DATE,
    VARCHAR, VARCHAR, BIGINT, VARCHAR
) TO authenticated;


-- =========================================================
-- 11. DATOS PROPIOS DE UNA SEMILLA EN EL PRODUCTO
-- =========================================================
--
-- Los agroquímicos tienen principio activo y concentración;
-- las semillas no tenían nada, y en el catálogo terminaban
-- siendo un nombre suelto.
--
-- `hibrido` acá NO reemplaza al de `detalle_semilla`: este es
-- la variedad que define al producto —DK 7210 es un maíz
-- concreto— y aquel es lo que vino en ESE palet, que puede
-- ser otra si el proveedor mandó una partida distinta con el
-- mismo nombre. El calibre sigue viviendo solo en el palet
-- porque cambia de una partida a otra.
--
-- =========================================================

ALTER TABLE public.producto
ADD COLUMN IF NOT EXISTS especie VARCHAR(100);

ALTER TABLE public.producto
ADD COLUMN IF NOT EXISTS hibrido VARCHAR(100);

COMMENT ON COLUMN public.producto.especie IS
    'Cultivo: maíz, soja, girasol. Solo para semillas.';

COMMENT ON COLUMN public.producto.hibrido IS
    'Variedad que define al producto (DK 7210). Solo para semillas. Distinto del híbrido de detalle_semilla, que es el de cada palet.';


COMMIT;
